### ISSUE TITLE
Upgrade to 1.14.4 cause ESP32 to lockup with DHT11 sensor 

### ISSUE THREAD

**Issue by faspina** [esphome/issues#1269] opened 2020-06-05 15:07 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32/NodeMcu32

**Affected component:**
DHT11 

https://esphome.io/components/sensor/dht.html

**Description of problem:**
DHT11 sensor was working with 1.14.3 , upgraded to 1.14.3 , NODEMCU lockedup and unresponsive,  took out the following code and it worked. Also simplified the DHT sensor and took out the filters, same result. Tried different GPIO , same result.  Works fine on my original nodemcu  

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: dht
    model: DHT11
    pin: GPIO21
    update_interval: 30s     
    temperature:
      name: "Office"
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
        - lambda: return x * (9.0/5.0) + 32.0; # report temperature in Fahrenheit
      unit_of_measurement: "°F"
    humidity:
      name: "Office Humidity"
      filters:
        - filter_out: nan
        - heartbeat: 15s
        - sliding_window_moving_average:
            window_size: 2
            send_every: 2
            send_first_at: 1
      accuracy_decimals: 1  
      

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by faspina** [comment] 2020-06-05 15:08
Should be noted this happens on two different devices since 1.14.4

**Comment by johnboiles** [comment] 2020-06-05 15:47
I'm also getting an ESP32 lockup with the DHT22 after upgrading to 1.14.4. I pulled my ESP32 down from the shelf, plugged in a USB cable, and uploaded the esphome firmware again to get the logs.

@faspina could you connect with a usb cable and try to re-install your esphome firmware and post the logs? That will help us be certain you and I are seeing the same issue. I think it's very likely that it's the exact same thing.

Downgrading to 1.14.3 and reinstalling solves the issue for me.

[This](https://github.com/johnboiles/homeassistant-config/blob/master/esphome/air_sensor.yaml) is the esphome yaml I'm using.

<details>
  <summary>Click to expand logs!</summary>

```  
> esphome air_sensor.yaml run
INFO Reading configuration air_sensor.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d air_sensor
Processing air_sensor (board: nodemcu-32s; framework: arduino; platform: espressif32@1.12.1)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif32 3.10004.200129 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <Wire> 1.0.1
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling .pioenvs/air_sensor/src/main.cpp.o
Linking .pioenvs/air_sensor/firmware.elf
Retrieving maximum program size .pioenvs/air_sensor/firmware.elf
Checking size .pioenvs/air_sensor/firmware.elf
Building .pioenvs/air_sensor/firmware.bin
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  13.2% (used 43216 bytes from 327680 bytes)
Flash: [======    ]  55.6% (used 910354 bytes from 1638400 bytes)
========================================================================== [SUCCESS] Took 6.90 seconds ==========================================================================
INFO Successfully compiled program.
Found multiple options, please choose one:
  [1] /dev/cu.usbserial-0001 (CP2102 USB to UART Bridge Controller - CP2102 USB to UART Bridge Controller)
  [2] Over The Air (air_sensor.local)
(number): 1
INFO Running:  platformio run -d air_sensor -t upload --upload-port /dev/cu.usbserial-0001
Processing air_sensor (board: nodemcu-32s; framework: arduino; platform: espressif32@1.12.1)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif32 3.10004.200129 (1.0.4)
 - tool-esptoolpy 1.20600.0 (2.6.0)
 - tool-mkspiffs 2.230.0 (2.30)
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <Wire> 1.0.1
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Retrieving maximum program size .pioenvs/air_sensor/firmware.elf
Checking size .pioenvs/air_sensor/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  13.2% (used 43216 bytes from 327680 bytes)
Flash: [======    ]  55.6% (used 910354 bytes from 1638400 bytes)
Configuring upload protocol...
AVAILABLE: esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Use manually specified: /dev/cu.usbserial-0001
Uploading .pioenvs/air_sensor/firmware.bin
Serial port /dev/cu.usbserial-0001
Connecting........_____....._____.....___
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 3c:71:bf:fb:e6:64
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 15872 bytes to 10319...

Writing at 0x00001000... (100 %)
Wrote 15872 bytes (10319 compressed) at 0x00001000 in 0.3 seconds (effective 497.8 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 143...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (143 compressed) at 0x00008000 in 0.0 seconds (effective 907.8 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 2892.0 kbit/s)...
Hash of data verified.
Compressed 910464 bytes to 507774...

Writing at 0x00010000... (3 %)
Writing at 0x00014000... (6 %)
Writing at 0x00018000... (9 %)
Writing at 0x0001c000... (12 %)
Writing at 0x00020000... (16 %)
Writing at 0x00024000... (19 %)
Writing at 0x00028000... (22 %)
Writing at 0x0002c000... (25 %)
Writing at 0x00030000... (29 %)
Writing at 0x00034000... (32 %)
Writing at 0x00038000... (35 %)
Writing at 0x0003c000... (38 %)
Writing at 0x00040000... (41 %)
Writing at 0x00044000... (45 %)
Writing at 0x00048000... (48 %)
Writing at 0x0004c000... (51 %)
Writing at 0x00050000... (54 %)
Writing at 0x00054000... (58 %)
Writing at 0x00058000... (61 %)
Writing at 0x0005c000... (64 %)
Writing at 0x00060000... (67 %)
Writing at 0x00064000... (70 %)
Writing at 0x00068000... (74 %)
Writing at 0x0006c000... (77 %)
Writing at 0x00070000... (80 %)
Writing at 0x00074000... (83 %)
Writing at 0x00078000... (87 %)
Writing at 0x0007c000... (90 %)
Writing at 0x00080000... (93 %)
Writing at 0x00084000... (96 %)
Writing at 0x00088000... (100 %)
Wrote 910464 bytes (507774 compressed) at 0x00010000 in 12.7 seconds (effective 572.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
========================================================================== [SUCCESS] Took 29.82 seconds ==========================================================================
INFO Successfully uploaded program.
INFO Starting log output from /dev/cu.usbserial-0001 with baud rate 115200
[08:25:02]\x96\x82\xc2\xcdfff001c,len:1044
[08:25:02]load:0x40078000,len:8896
[08:25:02]load:0x40080400,len:5828
[08:25:02]entry 0x400806ac
[08:25:03][I][logger:156]: Log initialized
[08:25:03][C][ota:364]: There have been 5 suspected unsuccessful boot attempts.
[08:25:03][I][app:028]: Running through setup()...
[08:25:03][C][uart:022]: Setting up UART...
[08:25:03][C][uart:022]: Setting up UART...
[08:25:03][D][mhz19:075]: MHZ19 Disabling automatic baseline calibration
[08:25:03][C][dht:011]: Setting up DHT...
[08:25:03][C][wifi:033]: Setting up WiFi...
[08:25:03][I][wifi:193]: WiFi Connecting to 'BoilesIOT'...
[08:25:03][D][ccs811:077]: Got co2=0 ppm, tvoc=0 ppb, baseline=0x2FC2
[08:25:03][D][sensor:092]: 'CCS811 eCO2 Value': Sending state 0.00000 ppm with 0 decimals of accuracy
[08:25:03][D][sensor:092]: 'CCS811 Total Volatile Organic Compound': Sending state 0.00000 ppb with 0 decimals of accuracy
[08:25:03][D][dht:048]: Got Temperature=22.8°C Humidity=46.7%
[08:25:03][D][sensor:092]: 'DHT22 Temperature': Sending state 22.80000 °C with 1 decimals of accuracy
[08:25:03][D][sensor:092]: 'DHT22 Humidity': Sending state 46.70000 % with 0 decimals of accuracy
[08:25:03]Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
[08:25:03]Core 1 register dump:
[08:25:03]PC      : 0x4000bff0  PS      : 0x00060a34  A0      : 0x8008aa94  A1      : 0x3ffb1950
INFO Need to fetch platformio IDE-data, please stand by
INFO Running:  platformio run -d air_sensor -t idedata
[08:25:04]A2      : 0x00000003  A3      : 0x00060a23  A4      : 0x00060a23  A5      : 0x3ffb8d08
[08:25:04]A6      : 0x400de0d8  A7      : 0x00000000  A8      : 0x800d7ab4  A9      : 0x3ffb1a20
[08:25:04]A10     : 0x3ffb8c30  A11     : 0x3ffb1a83  A12     : 0x00000009  A13     : 0x40475999
[08:25:04]A14     : 0x3ffb9378  A15     : 0x3ffb1a0c  SAR     : 0x0000000a  EXCCAUSE: 0x00000006
[08:25:04]EXCVADDR: 0x00000000  LBEG    : 0x4016050c  LEND    : 0x40160516  LCOUNT  : 0x00000000
[08:25:04]
[08:25:04]Backtrace: 0x4000bff0:0x3ffb1950 0x4008aa91:0x3ffb1960 0x40089863:0x3ffb1980 0x400eae21:0x3ffb19a0 0x400e89b9:0x3ffb19c0 0x401605a5:0x3ffb19e0 0x400d9693:0x3ffb1a00 0x400d9759:0x3ffb1a20 0x400d7ab1:0x3ffb1a40 0x400d7ad1:0x3ffb1a60 0x40160789:0x3ffb1ab0 0x40081437:0x3ffb1ad0 0x400dd4a3:0x3ffb1b00 0x400dfd7a:0x3ffb1b50 0x400eb3db:0x3ffb1fb0 0x40089915:0x3ffb1fd0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x4008aa91: vTaskExitCritical at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:3507
WARNING Decoded 0x40089863: uxQueueMessagesWaiting at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1996
WARNING Decoded 0x400eae21: uartAvailable at /Users/johnboiles/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-uart.c:411
WARNING Decoded 0x400e89b9: HardwareSerial::available() at /Users/johnboiles/.platformio/packages/framework-arduinoespressif32/cores/esp32/HardwareSerial.cpp:158
WARNING Decoded 0x401605a5: esphome::uart::UARTComponent::available() at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/components/uart/uart.cpp:102
WARNING Decoded 0x400d9693: esphome::uart::UARTComponent::check_read_timeout_(unsigned int) at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/components/uart/uart.cpp:94
WARNING Decoded 0x400d9759: esphome::uart::UARTComponent::read_array(unsigned char*, unsigned int) at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/components/uart/uart.cpp:80
WARNING Decoded 0x400d7ab1: esphome::uart::UARTDevice::read_array(unsigned char*, unsigned int) at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/components/uart/uart.h:97
 (inlined by) esphome::mhz19::MHZ19Component::mhz19_write_command_(unsigned char const*, unsigned char*) at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/components/mhz19/mhz19.cpp:90
WARNING Decoded 0x400d7ad1: esphome::mhz19::MHZ19Component::update() at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/components/uart/uart.h:97
WARNING Decoded 0x40160789: std::_Function_handler<void (), esphome::PollingComponent::call_setup()::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/core/component.cpp:111
 (inlined by) _M_invoke at /Users/johnboiles/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/functional:1871
WARNING Decoded 0x40081437: std::function<void ()>::operator()() const at /Users/johnboiles/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_vector.h:932
 (inlined by) esphome::Scheduler::call() at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/core/scheduler.cpp:137
WARNING Decoded 0x400dd4a3: esphome::Application::setup() at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/core/application.cpp:47
WARNING Decoded 0x400dfd7a: setup() at /Users/johnboiles/Programming/homeassistant-config/esphome/air_sensor/src/esphome/components/uart/uart.h:97
WARNING Decoded 0x400eb3db: loopTask(void*) at /Users/johnboiles/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:14
WARNING Decoded 0x40089915: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[08:25:04]
[08:25:04]Core 0 register dump:
[08:25:04]PC      : 0x4012df2b  PS      : 0x00060934  A0      : 0x8012e021  A1      : 0x3ffaf6a0
WARNING Decoded 0x4012df2b: hmac_sha1_vector at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/sha1.c:70 (discriminator 1)
[08:25:04]A2      : 0x3ffaf6fc  A3      : 0x0000000e  A4      : 0x00000001  A5      : 0x3ffaf76c
[08:25:04]A6      : 0x3ffaf768  A7      : 0x3ffaf7c8  A8      : 0x0000003f  A9      : 0x00000028
[08:25:04]A10     : 0x00000036  A11     : 0x00000000  A12     : 0x0000000e  A13     : 0x3ffaf70a
[08:25:04]A14     : 0x00000066  A15     : 0x00000066  SAR     : 0x00000018  EXCCAUSE: 0x00000006
[08:25:04]EXCVADDR: 0x00000000  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0xffffffff
[08:25:04]
[08:25:04]Backtrace: 0x4012df2b:0x3ffaf6a0 0x4012e01e:0x3ffaf760 0x4012fca5:0x3ffaf790 0x4012fd3b:0x3ffaf800 0x4015000d:0x3ffaf850 0x4015110e:0x3ffaf870 0x4015111d:0x3ffaf8b0 0x401168dd:0x3ffaf8d0 0x40116cec:0x3ffaf910 0x401179dd:0x3ffaf980 0x40117a96:0x3ffaf9d0 0x40112fa5:0x3ffafa20 0x401132c0:0x3ffafa70 0x401161c9:0x3ffafa90 0x401161ea:0x3ffafab0 0x40115da8:0x3ffafad0 0x40116072:0x3ffafaf0 0x4009034f:0x3ffafb10 0x40089915:0x3ffafb50
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x4012df2b: hmac_sha1_vector at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/sha1.c:70 (discriminator 1)
WARNING Decoded 0x4012e01e: hmac_sha1 at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/sha1.c:111
WARNING Decoded 0x4012fca5: pbkdf2_sha1_f at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/sha1-pbkdf2.c:54
WARNING Decoded 0x4012fd3b: pbkdf2_sha1 at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/wpa_supplicant/src/crypto/sha1-pbkdf2.c:91
WARNING Decoded 0x4015000d: wpa_set_bss
WARNING Decoded 0x4015110e: wpa_config_bss
WARNING Decoded 0x4015111d: wpa_sta_connect
WARNING Decoded 0x401168dd: cnx_sta_connect_led_timer_cb
WARNING Decoded 0x40116cec: cnx_sta_connect_led_timer_cb
WARNING Decoded 0x401179dd: cnx_remove_all_rc
WARNING Decoded 0x40117a96: cnx_start_handoff_cb
WARNING Decoded 0x40112fa5: clear_bss_queue
WARNING Decoded 0x401132c0: scan_inter_channel_timeout_process
WARNING Decoded 0x401161c9: chm_end_op
WARNING Decoded 0x401161ea: chm_end_op_timeout_process
WARNING Decoded 0x40115da8: wifi_station_stop
WARNING Decoded 0x40116072: ieee80211_timer_do_process
WARNING Decoded 0x4009034f: ppTask
WARNING Decoded 0x40089915: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[08:25:05]
[08:25:05]Rebooting...
```
</details>

**Comment by faspina** [comment] 2020-06-05 16:43
I am running ESPhome on docker on a unraid server, so I have to plug a cable in and pull my nodemcu in . may take me a bit to get around to it its probably the same issue

**Comment by mario-tux** [comment] 2020-06-05 17:23
The same here with DHT2 on ESP32 working with previous release.

**Comment by mbo18** [comment] 2020-06-06 07:50
Same here, ESP32, DHT22, ESPHome 1.14.4. Disabling the DHT sensor has solved this issue but no more temp and humidity report :(

**Comment by asadenton** [comment] 2020-06-07 01:53
I am seeing this too. 1.14.4 works fine on most of my devices but the one that has a DHT and Dallas is failing if I include either of those in the config. I am getting the same error message as above :"Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)". I think [1276](https://github.com/esphome/issues/issues/1276) is also related

**Comment by csmart** [comment] 2020-06-07 05:59
See https://github.com/esphome/issues/issues/1276#issuecomment-640146210

**Comment by Gymnae** [comment] 2020-06-07 09:12
Even though the devices did not appear in home assistant nor esphome I was able to flash them without DHT11 sensor code via OTA and bring them back to properly reporting themselves. 
This could be a workaround for the moment.

**Comment by glmnet** [comment] 2020-06-14 16:14
Duplicate of #1276

**Closed by glmnet** 2020-06-14 16:14 UTC
