### ISSUE TITLE
migrating sonoff rf bridge 433 from tasmota to esphome

### ISSUE THREAD

**Issue by lpt2007** [esphome/issues#777] opened 2019-10-28 10:01 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

sonoff rf bridge 433 wit tasmota firmware
**ESP (ESP32/ESP8266, Board/Sonoff):**

![20191026_184839](https://user-images.githubusercontent.com/38924279/67668912-23dfc900-f971-11e9-956f-ac4b1734bc43.jpg)
![20191026_184856](https://user-images.githubusercontent.com/38924279/67668931-29d5aa00-f971-11e9-8166-acb3e815b388.jpg)

**Affected component:**

**Description of problem:**
Question 1:
I don't know If I must do hardware hack for esphome to work on this device?

If answer is yes. Where can I find howto for my device?

Question 2:
Can I flash my device directly from tasmota?

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment] 2019-10-28 12:09
Duplicate of https://github.com/esphome/feature-requests/issues/358

1. Yes, that is necessary. I think the tasmota docs had something about it but I don't know.
2. See migrating from tasmota guide.

**Closed by OttoWinter** 2019-10-28 12:09 UTC
