### ISSUE TITLE
Crash on http_request.get when ethernet component used

### ISSUE THREAD

**Issue by kiklhorn** [esphome/issues#5040] opened 2023-10-27 07:20 UTC
### The problem

Very basic config used, http_request.get crashing when ehternet component is used, on wifi working without crash.

### Which version of ESPHome has the issue?

2023.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.0b0

### What platform are you using?

ESP32

### Board

https://github.com/LaskaKit/ESPlan

### Component causing the issue

http_request

### Example YAML snippet

```yaml
esphome:
  name: lanbtproxy
  friendly_name: LANbtproxy

esp32:
  board: esp32dev
  framework:
    type: arduino
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "VRcVmSnV+7wh21jv5NBjk4qDQau5KSnWnmWaR5jfmVg="

ota:
  password: "9cdea155d7d8cf15cbe417b607f1f3ad"

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
#   use_address: 192.168.199.163

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic

http_request:
  id: lwq
  useragent: esphome/device
  timeout: 10s

interval:
  - interval: 2min
    then:
    - http_request.get:
        url: https://esphome.io
        headers:
          Content-Type: application/json
        verify_ssl: false
        on_response:
          then:
            - logger.log:
                format: 'Response status: %d, Duration: %u ms'
                args:
                  - status_code
                  - duration_ms
```

### Anything in the logs that might be useful for us?

```txt
Crashing when ethernet component is used:

INFO ESPHome 2023.10.3
INFO Reading configuration /config/esphome/lanbtproxy.yaml...
INFO Starting log output from lanbtproxy.local using esphome API
INFO Successfully connected to lanbtproxy.local
[08:53:28][I][app:102]: ESPHome version 2023.10.3 compiled on Oct 27 2023, 08:52:19
[08:53:28][I][app:104]: Project esphome.bluetooth-proxy version 1.0
[08:53:28][C][logger:416]: Logger:
[08:53:28][C][logger:417]:   Level: DEBUG
[08:53:28][C][logger:418]:   Log Baud Rate: 115200
[08:53:28][C][logger:420]:   Hardware UART: UART0
[08:53:28][C][safe_mode.button:022]: Safe Mode Button 'Safe Mode Boot'
[08:53:28][C][safe_mode.button:022]:   Icon: 'mdi:restart-alert'
[08:53:28][C][ethernet:221]: Ethernet:
[08:53:28][C][ethernet:353]:   IP Address: 192.168.199.163
[08:53:28][C][ethernet:354]:   Hostname: 'lanbtproxy'
[08:53:28][C][ethernet:355]:   Subnet: 255.255.255.0
[08:53:28][C][ethernet:356]:   Gateway: 192.168.199.1
[08:53:28][C][ethernet:361]:   DNS1: 192.168.199.1
[08:53:28][C][ethernet:362]:   DNS2: 0.0.0.0
[08:53:28][C][ethernet:382]:   MAC Address: CC:DB:A7:FE:18:CB
[08:53:28][C][ethernet:387]:   Is Full Duplex: YES
[08:53:28][C][ethernet:392]:   Link Speed: 100
[08:53:28][C][ethernet:226]:   MDC Pin: 23
[08:53:28][C][ethernet:227]:   MDIO Pin: 18
[08:53:28][C][ethernet:228]:   Type: LAN8720
[08:53:28][C][ethernet:229]:   PHY addr: 0
[08:53:28][C][mdns:115]: mDNS:
[08:53:28][C][mdns:116]:   Hostname: lanbtproxy
[08:53:28][C][ota:097]: Over-The-Air Updates:
[08:53:28][C][ota:098]:   Address: lanbtproxy.local:3232
[08:53:28][C][ota:101]:   Using Password.
[08:53:28][C][api:138]: API Server:
[08:53:28][C][api:139]:   Address: lanbtproxy.local:6053
[08:53:28][C][api:141]:   Using noise encryption: YES
[08:53:28][C][http_request:014]: HTTP Request:
[08:53:28][C][http_request:015]:   Timeout: 10000ms
[08:53:28][C][http_request:016]:   User-Agent: esphome/device
[08:53:28][C][http_request:017]:   Follow Redirects: 1
[08:53:28][C][http_request:018]:   Redirect limit: 3
[08:54:00][D][main:203]: Response status: -1, Duration: 5 ms
[08:54:00][W][http_request:087]: HTTP Request failed; URL: https://esphome.io/; Error: connection refused; Duration: 5 ms
WARNING lanbtproxy.local: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for lanbtproxy.local
WARNING Disconnected from API
INFO Successfully connected to lanbtproxy.local
[08:54:15][D][api:102]: Accepted 192.168.199.99
[08:54:15][D][api.connection:1032]: Home Assistant 2023.11.0b0 (192.168.199.99): Connected successfully

Working when wifi component is used:

INFO ESPHome 2023.10.3
INFO Reading configuration /config/esphome/lanbtproxy.yaml...
INFO Starting log output from lanbtproxy.local using esphome API
INFO Successfully connected to lanbtproxy.local
[08:45:20][I][app:102]: ESPHome version 2023.10.3 compiled on Oct 27 2023, 08:43:41
[08:45:20][I][app:104]: Project esphome.bluetooth-proxy version 1.0
[08:45:20][C][wifi:546]: WiFi:
[08:45:20][C][wifi:382]:   Local MAC: CC:DB:A7:FE:18:C8
[08:45:20][C][wifi:383]:   SSID: 'KIoT'[redacted]
[08:45:20][C][wifi:384]:   IP Address: 192.168.199.46
[08:45:20][C][wifi:386]:   BSSID: B6:95:75:B0:0E:24[redacted]
[08:45:20][C][wifi:387]:   Hostname: 'lanbtproxy'
[08:45:20][C][wifi:389]:   Signal strength: -41 dB ▂▄▆█
[08:45:20][C][wifi:393]:   Channel: 11
[08:45:20][C][wifi:394]:   Subnet: 255.255.255.0
[08:45:20][C][wifi:395]:   Gateway: 192.168.199.1
[08:45:20][C][wifi:396]:   DNS1: 192.168.199.1
[08:45:20][C][wifi:397]:   DNS2: 0.0.0.0
[08:45:20][C][logger:416]: Logger:
[08:45:20][C][logger:417]:   Level: DEBUG
[08:45:20][C][logger:418]:   Log Baud Rate: 115200
[08:45:20][C][logger:420]:   Hardware UART: UART0
[08:45:20][C][safe_mode.button:022]: Safe Mode Button 'Safe Mode Boot'
[08:45:21][C][safe_mode.button:022]:   Icon: 'mdi:restart-alert'
[08:45:21][C][mdns:115]: mDNS:
[08:45:21][C][mdns:116]:   Hostname: lanbtproxy
[08:45:21][C][ota:097]: Over-The-Air Updates:
[08:45:21][C][ota:098]:   Address: lanbtproxy.local:3232
[08:45:21][C][ota:101]:   Using Password.
[08:45:21][C][api:138]: API Server:
[08:45:21][C][api:139]:   Address: lanbtproxy.local:6053
[08:45:21][C][api:141]:   Using noise encryption: YES
[08:45:21][C][http_request:014]: HTTP Request:
[08:45:21][C][http_request:015]:   Timeout: 10000ms
[08:45:21][C][http_request:016]:   User-Agent: esphome/device
[08:45:21][C][http_request:017]:   Follow Redirects: 1
[08:45:21][C][http_request:018]:   Redirect limit: 3
[08:46:01][D][main:215]: Response status: 200, Duration: 1293 ms
[08:46:01][D][http_request:099]: HTTP Request completed; URL: https://esphome.io/; Code: 200; Duration: 1293 ms
[08:46:01][W][component:214]: Component interval took a long time for an operation (1.31 s).
[08:46:01][W][component:215]: Components should block for at most 20-30ms.
[08:48:00][D][main:215]: Response status: -7, Duration: 254 ms
[08:48:00][W][http_request:087]: HTTP Request failed; URL: https://esphome.io/; Error: no HTTP server; Duration: 254 ms
[08:48:00][W][component:214]: Component interval took a long time for an operation (0.28 s).
[08:48:00][W][component:215]: Components should block for at most 20-30ms.
[08:49:14][I][ota:117]: Boot seems successful, resetting boot loop counter.
[08:49:14][D][esp32.preferences:114]: Saving 1 preferences to flash...
[08:49:14][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[08:50:00][D][main:215]: Response status: 200, Duration: 742 ms
[08:50:00][D][http_request:099]: HTTP Request completed; URL: https://esphome.io/; Code: 200; Duration: 742 ms
[08:50:00][W][component:214]: Component interval took a long time for an operation (0.77 s).
[08:50:00][W][component:215]: Components should block for at most 20-30ms.
```

**Comment by ssieb** [comment] 2023-10-27 07:32
Duplicate of https://github.com/esphome/issues/issues/5039

**Closed by ssieb** 2023-10-27 07:32 UTC
