### ISSUE TITLE
Home Assistant ESPHome - Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead

### ISSUE THREAD

**Issue by JSEHV** [esphome/issues#2424] opened 2021-09-15 08:49 UTC
### The problem

21-09-15 10:26:39 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead. Please report this to the maintainer of ESPHome

### What is version of Home Assistant Core has the issue?

core-2021.9.6

### What was the last working version of Home Assistant Core?

core-2021.9.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

ESPHome

### Additional information

[https://github.com/home-assistant/core/issues/56249](https://github.com/home-assistant/core/issues/56249)

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant OS 6.4 / core-2021.9.6

### What platform are you using?

ESP8266

**Comment by oxan** [comment] 2021-09-15 12:56
Duplicate of #2380.

**Closed by oxan** 2021-09-15 12:56 UTC
