### ISSUE TITLE
update all doesn´t work

### ISSUE THREAD

**Issue by santa81** [esphome/issues#2282] opened 2021-07-30 20:17 UTC
### The problem

if i want to update all devices in esphome dashboard i get an error:
`WARNING Calling ESPHome with the configuration before the command is deprecated and will be removed in the future. 
WARNING Please instead use:
WARNING    esphome --dashboard config update-all
INFO Reading configuration update-all...
ERROR Error while reading config: Invalid YAML syntax:

Error reading file update-all: [Errno 2] No such file or directory: 'update-all'`

![esphome](https://user-images.githubusercontent.com/18234371/127707030-4df62378-2968-4fa3-bdcf-0e18860d239e.png)

### What is version of ESPHome has the issue?

1.20.3

### What type of installation are you using?

pip

### What platform are you using?

ESP8266

**Comment by OttoWinter** [comment] 2021-08-01 10:10
Duplicate of https://github.com/esphome/issues/issues/2195

**Closed** 2021-09-13 07:37 UTC
Labels: Project: ESPHome-Dashboard
