### ISSUE TITLE
SNTP timezone TZ database interpretation is wrong

### ISSUE THREAD

**Issue by marcellomaia** [esphome/issues#4273] opened 2023-03-03 18:20 UTC
### The problem

using a sntp component with a timezone configuration is not correct.  When I configure it to use America/Sao_Paulo is not been condigured to be GMT-3 as expected.  I'm getting GTM+3.  

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

custom board based on ESP32 chip

### Component causing the issue

time/sntp

### Example YAML snippet

```yaml
time:
  - platform: sntp
    timezone: "America/Sao_Paulo"
    #timezone: "Etc/GMT-3"
    id: sntp_time
    on_time:
      - seconds: 0
        minutes: '*'
        then:
        - lambda: |-
            id(sntp_time).dump_config();
            auto time_text = id(sntp_time).now().strftime("%I:%M %p");          
            auto date_text = id(sntp_time).now().strftime("%e %b");    
            ESP_LOGD("sntp", "DATE/TIME %s %s", date_text.c_str(), time_text.c_str());
            auto time_text2 = id(sntp_time).utcnow().strftime("%I:%M %p");          
            auto date_text2 = id(sntp_time).utcnow().strftime("%e %b");    
            ESP_LOGD("sntp", "DATE/TIME 2 %s %s", date_text2.c_str(), time_text2.c_str());
```

### Anything in the logs that might be useful for us?

```txt
This is the log I get with the configuration above.  The local time in fact is 15h15 as shown on the start of the log entry,  the component seem pretty confused. It's adding three hours over UTC as if it were GMT+3 instead of GMT-3 as it should.

15:15:57	[C]	[sntp:053]	SNTP Time:
15:15:57	[C]	[sntp:054]	  Server 1: '0.pool.ntp.org'
15:15:57	[C]	[sntp:055]	  Server 2: '1.pool.ntp.org'
15:15:57	[C]	[sntp:056]	  Server 3: '2.pool.ntp.org'
15:15:57	[C]	[sntp:057]	  Timezone: '<-03>3'
15:15:57	[D]	[sntp:237]	DATE/TIME  3 Mar 09:16 PM
15:15:57	[D]	[sntp:240]	DATE/TIME 2  3 Mar 06:16 PM
```

**Comment by ssieb** [comment] 2023-03-03 18:45
Duplicate of https://github.com/esphome/issues/issues/3769

**Closed by ssieb** 2023-03-03 18:45 UTC
