### ISSUE TITLE
error line in homeassistant.log: WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead)

### ISSUE THREAD

**Issue by Lucus123** [esphome/issues#2399] opened 2021-09-08 09:29 UTC
### The problem

The problem
Problem/Motivation
homeassistant logs show the use of a deprecated config parameter in the addon

Expected behavior
no errors

Actual behavior
error line in homeassistant.log: WARNING (MainThread) [supervisor.addons.validate] Add-on config 'snapshot_exclude' is deprecated, 'backup_exclude' should be used instead)

Steps to reproduce
check homeassistant log on startup

Proposed changes
replace snapshot_exclude with backup_exclude

What is version of Home Assistant Core has the issue?
core-2021.9.4

What was the last working version of Home Assistant Core?
No response

What type of installation are you running?
Home Assistant Supervised

Integration causing the issue
ESPHome

Link to integration documentation on our website
https://www.home-assistant.io/integrations/esphome

Example YAML snippet
No response

Anything in the logs that might be useful for us?
No response

Additional information
No response

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

**Comment by oxan** [comment] 2021-09-08 09:32
Duplicate of #2380.

**Closed by oxan** 2021-09-08 09:32 UTC
