### ISSUE TITLE
SM16716 compile error

### ISSUE THREAD

**Issue by l3ok** [esphome/issues#878] opened 2019-11-24 10:00 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome 1.13.0 on HassOS 2.12

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266 with SM16716 Led driver

**Affected component:**

https://esphome.io/components/output/sm16716.html

**Description of problem:**

Compile fails with below logs

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: light_os_gate_il
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "###"
  password: "###"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


sm16716:
  data_pin: GPIO14
  clock_pin: GPIO4
  num_channels: 3
  num_chips: 1

output:
  - platform: sm16716
    id: output_red
    channel: 0
    power_supply: rgb_power
  - platform: sm16716
    id: output_green
    channel: 1
    power_supply: rgb_power
  - platform: sm16716
    id: output_blue
    channel: 2
    power_supply: rgb_power
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12
light:
  - platform: rgbww
    name: Inside left gate light
    id: light
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

power_supply:
  - id: rgb_power
    pin: GPIO13
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
INFO Reading configuration...
Failed config

sm16716: [source /config/esphome/light_os_gate_il.yaml:20]
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 11, in <module>
    load_entry_point('esphome', 'console_scripts', 'esphome')()
  File "/opt/esphome/esphome/__main__.py", line 483, in main
    return run_esphome(sys.argv)
  File "/opt/esphome/esphome/__main__.py", line 466, in run_esphome
    config = read_config(args.verbose)
  File "/opt/esphome/esphome/config.py", line 809, in read_config
    safe_print(indent(dump_dict(res, path)[0]))
  File "/opt/esphome/esphome/config.py", line 688, in dump_dict
    ret += u'\n' + color('bold_red', _format_vol_invalid(error, config)) + u'\n'
  File "/opt/esphome/esphome/config.py", line 615, in _format_vol_invalid
    elif u'extra keys not allowed' in text_type(ex):
  File "/opt/esphome/esphome/config_validation.py", line 622, in _vol_invalid_unicode
    output = decode_text(self.message)
  File "/opt/esphome/esphome/py_compat.py", line 81, in decode_text
    return unicode(data, encoding=encoding, errors=errors)
TypeError: decoding Unicode is not supported
```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment] 2019-11-26 17:56
> ESPHome 1.13.0 on HassOS 2.12

The latest version is 1.14.3, please use that.

The issue is also fixed in that version.

**Closed by OttoWinter** 2019-11-26 17:56 UTC
