### ISSUE TITLE
Feature request: Support Platformio 4.0 / Python 3

### ISSUE THREAD

**Issue by grzeg8102** [esphome/issues#570] opened 2019-08-07 13:54 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip
**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32
**Affected component:**
all

**Description of problem:**
Feature request:
I think would be good to start working on support for Platformio 4.0, which finally supports Python 3.5+. Python 2.7 will be deprecated in less 5 months now. Seems platformio Team understood the impact and added support for Python 3.5. So the only reason why esphome runs on top of python 2.7 would be gone forever (hopefully).

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment] 2019-08-07 13:57
Duplicate of https://github.com/esphome/feature-requests/issues/320

**Comment by glmnet** [comment] 2019-08-07 13:59
FYI: there is a feature-request specific issue tracker.

**Closed by glmnet** 2019-08-07 13:59 UTC

**Comment by fake-name** [comment] 2019-08-29 03:37
Python 3 is EoL in 5 months. 

This isn't a feature at this point, it's a bug.

**Comment by glmnet** [comment] 2019-08-29 03:53
Yes. If esphome isn’t based on python 3 at this moment is mostly because platform io wasn’t supporting it before. People really want to get it working ASAP but there is a large user base with very different implementation scenarios and rush will not help here.

**Comment by fake-name** [comment] 2019-08-29 03:55
I wound up cloning https://github.com/fabaff/esphome/tree/py3 and am having a poke.
