### ISSUE TITLE
warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]

### ISSUE THREAD

**Issue by bernardesarthur** [esphome/issues#6191] opened 2024-08-22 16:29 UTC
### The problem

I don't know what it is, but I've check my code and I don't find any problems with config.

The whole error message is below:

```
src/esphome/core/bytebuffer.cpp: In member function 'float esphome::ByteBuffer::get_float()':
src/esphome/core/bytebuffer.cpp:86:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   86 |   return *(float *) &value;
      |           ^~~~~~~~~~~~~~~~
src/esphome/core/bytebuffer.cpp: In member function 'void esphome::ByteBuffer::put_float(float)':
src/esphome/core/bytebuffer.cpp:129:61: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  129 | void ByteBuffer::put_float(float value) { this->put_uint32(*(uint32_t *) &value); }
      |                                                             ^~~~~~~~~~~~~~~~~~~
```
      
Until now I don't see any problem with my devices.

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.8.0

### What platform are you using?

ESP8266

### Board

Sonoff Basic

**Comment by garry0garry** [comment] 2024-08-22 18:43
ESPHome 2024.8.0

```
src/esphome/core/bytebuffer.cpp: In member function 'float esphome::ByteBuffer::get_float()':
src/esphome/core/bytebuffer.cpp:86:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   86 |   return *(float *) &value;
      |           ^~~~~~~~~~~~~~~~
src/esphome/core/bytebuffer.cpp: In member function 'void esphome::ByteBuffer::put_float(float)':
src/esphome/core/bytebuffer.cpp:129:61: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  129 | void ByteBuffer::put_float(float value) { this->put_uint32(*(uint32_t *) &value); }
      |                                                             ^~~~~~~~~~~~~~~~~~~
```

**Comment by slongano** [comment] 2024-08-22 19:03
This happens to me too. Snippet:
Compiling .pioenvs/interruttore-sala-piccola/src/esphome/core/bytebuffer.cpp.o
src/esphome/core/bytebuffer.cpp: In member function 'float esphome::ByteBuffer::get_float()':
src/esphome/core/bytebuffer.cpp:86:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   86 |   return *(float *) &value;
      |           ^~~~~~~~~~~~~~~~
src/esphome/core/bytebuffer.cpp: In member function 'void esphome::ByteBuffer::put_float(float)':
src/esphome/core/bytebuffer.cpp:129:61: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  129 | void ByteBuffer::put_float(float value) { this->put_uint32(*(uint32_t *) &value); }
      |                                                             ^~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/interruttore-sala-piccola/src/esphome/core/color.cpp.o

**Comment by moravszky** [comment] 2024-08-22 19:23
I get the same warning,
Core: 2024.8.2
HAOS: 13.1
ESPHome: 2024.8.0

esp32:
board: esp32dev
framework:
type: esp-idf
version: recommended

compile log:
src/esphome/core/bytebuffer.cpp: In member function 'float esphome::ByteBuffer::get_float()':
src/esphome/core/bytebuffer.cpp:86:11: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
return *(float ) &value;
^~~~~~~~~~~~~~~~
src/esphome/core/bytebuffer.cpp: In member function 'void esphome::ByteBuffer::put_float(float)':
src/esphome/core/bytebuffer.cpp:129:61: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
void ByteBuffer::put_float(float value) { this->put_uint32((uint32_t *) &value); }
^~~~~~~~~~~~~~~~~~~

**Comment by jesserockz** [comment] 2024-08-22 20:10
This is only a warning and is being fixed already.

**Comment by jesserockz** [comment] 2024-08-22 20:11
Duplicate of #6179

**Closed** 2024-08-22 20:11 UTC
