### ISSUE TITLE
esphome with SML isnt working anymore since esphome 2024.7.1, maybe " Fixes sml parser to process extended length lists with a number of items that is dividable by 16 #6148 " caused it

### ISSUE THREAD

**Issue by Simon566** [esphome/issues#6163] opened 2024-08-16 12:08 UTC
### The problem

i have a long running unchanged ESP32 reading my fairly common smart meter, this is running since 3 years , unchanged .

i updated esphome from 2024.6.4 to 2024.7.3 and recognized nothing is working anymore. i downgraded step by step and 2024.7.0 is working again.

i assume the commit above destroyed some SML functionality of my reader

### Which version of ESPHome has the issue?

2024.7.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.3.3

### What platform are you using?

ESP8266

### Board

nodemcu

### Component causing the issue

sml

### Anything in the logs that might be useful for us?

```txt
im not even getting logs / sensor output after the sensor boots
```

**Comment by eNBeWe** [comment] 2024-08-18 14:23
I think this should be fixed in the next release. (duplicate of #6091)

**Closed** 2024-08-26 06:48 UTC
