### ISSUE TITLE
Esphome fails to start produces a  TypeError

### ISSUE THREAD

**Issue by JCrankWV** [esphome/issues#591] opened 2019-08-16 02:07 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Python 2.7.10 clean venv install running on mac

**ESP (ESP32/ESP8266, Board/Sonoff):**

Have not gotten this far

**Affected component:**

entire script

**Description of problem:**

esphome 1.13.6 installed via pip with no errors
version 1.12.2 runs perfect under the same environment
when I try to run esphome I get the following error

```
(esphome)*****@iMac:~/python_venv/esphome$ esphome
Traceback (most recent call last):
  File "/Users/james/python_venv/esphome/bin/esphome", line 7, in <module>
    from esphome.__main__ import main
  File "/Users/james/python_venv/esphome/lib/python2.7/site-packages/esphome/__main__.py", line 10, in <module>
    from esphome import const, writer, yaml_util
  File "/Users/james/python_venv/esphome/lib/python2.7/site-packages/esphome/writer.py", line 7, in <module>
    from esphome.config import iter_components
  File "/Users/james/python_venv/esphome/lib/python2.7/site-packages/esphome/config.py", line 15, in <module>
    from esphome import core, core_config, yaml_util
  File "/Users/james/python_venv/esphome/lib/python2.7/site-packages/esphome/core_config.py", line 6, in <module>
    import esphome.config_validation as cv
  File "/Users/james/python_venv/esphome/lib/python2.7/site-packages/esphome/config_validation.py", line 1242, in <module>
    Optional(CONF_COMMAND_TOPIC): All(requires_component('mqtt'), subscribe_topic),
  File "/Users/james/python_venv/esphome/lib/python2.7/site-packages/esphome/voluptuous_schema.py", line 198, in extend
    ret = super(_Schema, self).extend(schema, extra=extra)
  File "/Users/james/python_venv/esphome/lib/python2.7/site-packages/voluptuous/schema_builder.py", line 782, in extend
    return result_cls(result, required=result_required, extra=result_extra)
TypeError: __init__() got an unexpected keyword argument 'required'

```

Python Version
```
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
```
**Problem-relevant YAML-configuration entries:**

```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by BrianGilbert** [comment] 2019-08-16 02:49
this error also occurs with Python 2.7.16

tested on both MacOS 10.14 and 10.15 beta same error on both.

**Comment by radunCZ** [comment] 2019-08-16 07:28
Same errors visible on fresh raspbian with Python 2.7.13 and 2.7.16 (under venv)

**Comment by radunCZ** [comment] 2019-08-16 07:37
cheked the modules version against the vorking environment and voluptous seems to be the issue. Once replaced the newest 0.11.7 by 0.11.5 from the working one, esphome is able to start.

**Comment by rradar** [comment] 2019-08-16 11:47
Had this issue yesterday on a linux machine as well.

To fix install voluptous in version 0.11.5 (neweset 0.11.7 which is installed automatically doesn't work)

**Comment by brandond** [comment] 2019-08-16 17:20
Duplicate of #580

**Closed by brandond** 2019-08-16 17:20 UTC

**Comment by SonnyJim** [comment] 2019-09-07 10:10
On a Pi Zero W running Hassbian I took a slightly approach, starting from the Pi user:

sudo -u homeassistant -H -s
source /srv/homeassistant/bin/activate
pip install voluptuous==0.11.5
pip install esphome

**Comment by neuman1812** [comment] 2019-09-27 20:00
Having the same issues.  I upgrade to python 3  and install followed the options from @dannysauer .  

Full log of what I did here: https://hastebin.com/ipozilahuy.sql

Steps: 
Install esphome
Uninstall voluptuous
install python-voluptuous

**Comment by martin3000** [comment] 2019-09-28 09:24
```
pip3 uninstall voluptuous
sudo apt install python3-voluptuous 

```
This fixed it in ubuntu.

**Comment by rmrfus** [comment] 2019-10-02 07:55
It appears that esphome works fine with 0.10.5

```
pip3 uninstall voluptuous
pip install --user voluptuous==0.10.5
```
