### ISSUE TITLE
Date / Time - Leap Year Variable

### ISSUE THREAD

**Issue by DMIllsUK** [esphome/issues#4597] opened 2023-06-22 17:10 UTC
### The problem

When I updated my ESPHome devices I see the following errors in the log.

**In file included from src/esphome/components/time/automation.h:5,**
                 from src/esphome/components/time/automation.cpp:1:
src/esphome/core/time.h:11:13: warning: 'bool esphome::is_leap_year(uint32_t)' declared 'static' but never defined [-Wunused-function]
   11 | static bool is_leap_year(uint32_t year);
      |             ^~~~~~~~~~~~
src/esphome/core/time.h:13:16: warning: 'uint8_t esphome::days_in_month(uint8_t, uint16_t)' declared 'static' but never defined [-Wunused-function]
   13 | static uint8_t days_in_month(uint8_t month, uint16_t year);
      |                ^~~~~~~~~~~~~
Compiling /data/easehold2-loft-light/.pioenvs/easehold2-loft-light/src/esphome/components/web_server/list_entities.cpp.o
In file included from src/esphome/components/time/real_time_clock.h:8,
                 from src/esphome/components/time/real_time_clock.cpp:1:
src/esphome/core/time.h:11:13: warning: 'bool esphome::is_leap_year(uint32_t)' declared 'static' but never defined [-Wunused-function]
   11 | static bool is_leap_year(uint32_t year);
      |             ^~~~~~~~~~~~
src/esphome/core/time.h:13:16: warning: 'uint8_t esphome::days_in_month(uint8_t, uint16_t)' declared 'static' but never defined [-Wunused-function]
   13 | static uint8_t days_in_month(uint8_t month, uint16_t year);

**In file included from src/esphome/components/time/real_time_clock.h:8,**
                 from src/esphome/components/sntp/sntp_component.h:4,
                 from src/esphome.h:47,
                 from src/main.cpp:3:
src/esphome/core/time.h:11:13: warning: 'bool esphome::is_leap_year(uint32_t)' declared 'static' but never defined [-Wunused-function]
   11 | static bool is_leap_year(uint32_t year);
      |             ^~~~~~~~~~~~
src/esphome/core/time.h:13:16: warning: 'uint8_t esphome::days_in_month(uint8_t, uint16_t)' declared 'static' but never defined [-Wunused-function]
   13 | static uint8_t days_in_month(uint8_t month, uint16_t year);

### Which version of ESPHome has the issue?

2023.6.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.2

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

time

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2023.6.0
INFO Reading configuration /config/esphome/easehold_4.yaml...
INFO Detected timezone 'Europe/London'
INFO Generating C++ source...
INFO Compiling app...
Processing easehold4-playroom-camera (board: esp01_1m; framework: arduino; platform: platformio/espressif8266@3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/api_connection.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/api_frame_helper.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/api_pb2.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/api_server.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/list_entities.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/proto.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/api/user_services.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/binary_sensor/automation.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/binary_sensor/filter.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/button/button.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/esp8266/core.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/esp8266/gpio.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/esp8266/preferences.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/json/json_util.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/logger/logger.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/md5/md5.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/mdns/mdns_component.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/mdns/mdns_host.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/network/util.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/restart/button/restart_button.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/safe_mode/button/safe_mode_button.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/sensor/automation.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/sensor/filter.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/sensor/sensor.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/shutdown/button/shutdown_button.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/sntp/sntp_component.cpp.o
In file included from src/esphome/components/time/real_time_clock.h:8,
                 from src/esphome/components/sntp/sntp_component.h:4,
                 from src/esphome/components/sntp/sntp_component.cpp:1:
src/esphome/core/time.h:11:13: warning: 'bool esphome::is_leap_year(uint32_t)' declared 'static' but never defined [-Wunused-function]
   11 | static bool is_leap_year(uint32_t year);
      |             ^~~~~~~~~~~~
src/esphome/core/time.h:13:16: warning: 'uint8_t esphome::days_in_month(uint8_t, uint16_t)' declared 'static' but never defined [-Wunused-function]
   13 | static uint8_t days_in_month(uint8_t month, uint16_t year);
      |                ^~~~~~~~~~~~~
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/socket/bsd_sockets_impl.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/socket/lwip_raw_tcp_impl.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/socket/socket.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/status/status_binary_sensor.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/switch/automation.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/switch/switch.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/text_sensor/filter.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/text_sensor/text_sensor.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/time/automation.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/time/real_time_clock.cpp.o
Compiling /data/easehold4-playroom-camera/.pioenvs/easehold4-playroom-camera/src/esphome/components/uptime/uptime_sensor.cpp.o
In file included from src/esphome/components/time/automation.h:5,
                 from src/esphome/components/time/automation.cpp:1:
src/esphome/core/time.h:11:13: warning: 'bool esphome::is_leap_year(uint32_t)' declared 'static' but never defined [-Wunused-function]
   11 | static bool is_leap_year(uint32_t year);
      |             ^~~~~~~~~~~~
src/esphome/core/time.h:13:16: warning: 'uint8_t esphome::days_in_month(uint8_t, uint16_t)' declared 'static' but never defined [-Wunused-function]
   13 | static uint8_t days_in_month(uint8_t month, uint16_t year);
      |                ^~~~~~~~~~~~~
```

**Comment by bkaufx** [comment] 2023-06-22 20:36
Duplicate of https://github.com/esphome/issues/issues/4581

**Closed** 2023-06-22 20:52 UTC
