### ISSUE TITLE
ESP32-C3 Disconnected reason='Auth Expired'

### ISSUE THREAD

**Issue by git-peterk** [esphome/issues#4893] opened 2023-09-18 18:43 UTC
### The problem

I was trying to compile a very minimalistic firmware to test ESPHome with my new ESP32-C3 boards.
I've tried 4 different boards so far, but none of them are able to connect to my Wi-Fi network. They all give the exact same error as shown in the log: `Event: Disconnected ssid='SMITH_HA' bssid=[redacted] reason='Auth Expired'`

I have many ESP32-D0 based boards that work flawlessly, but they all use the Arduino framework. This was the 1st time I was trying to use ESP-IDF, as I don't have access to the UART pins on these devices, so I could only use the USB_SERIAL_JTAG port. Regardless, I tried compiling a firmware with the Arduino framework (although I can't see the device logs that way), but the boards did not connect to the AP that way either.

Things I've tried so far (still with ESP-IDF) with no success:
- Get the boards closer to the AP
- Using various methods to power the boards
  PC's USB port, power bank, a wall power adapter
- Disabling power-save for Wi-Fi
  ```yaml
  wifi:
    # ...
    power_save_mode: none
  ```
- Explicitly setting BSSID of the AP
  ```yaml
  wifi:
    networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      bssid: XX:XX:XX:XX:XX:XX
  ```
- Connecting to a different Wi-Fi network

I also tried setting the board to AP mode, that way I can connect to the board using my phone, so the hardware portion of Wi-Fi should be operational on the boards.

Compile log shows no issues:
```
INFO ESPHome 2023.8.3
INFO Reading configuration /config/esphome/esphome-presence.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-presence (board: esp32-c3-devkitm-1; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5

...

Linking /data/esphome-presence/.pioenvs/esphome-presence/firmware.elf
RAM:   [=         ]   7.9% (used 25900 bytes from 327680 bytes)
Flash: [====      ]  43.6% (used 800128 bytes from 1835008 bytes)
Building /data/esphome-presence/.pioenvs/esphome-presence/firmware.bin
Creating esp32c3 image...
Successfully created esp32c3 image.
esp32_create_combined_bin(["/data/esphome-presence/.pioenvs/esphome-presence/firmware.bin"], ["/data/esphome-presence/.pioenvs/esphome-presence/firmware.elf"])
Wrote 0xd48a0 bytes to file /data/esphome-presence/.pioenvs/esphome-presence/firmware-factory.bin, ready to flash to offset 0x0
======================== [SUCCESS] Took 119.56 seconds ========================
INFO Successfully compiled program.
```

### Which version of ESPHome has the issue?

2023.8.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.09.2

### What platform are you using?

ESP32-IDF

### Board

esp32-c3-devkitm-1

### Component causing the issue

wifi

### Example YAML snippet

```yaml
esphome:
  name: esphome-presence
  friendly_name: ESPHome Presence
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Presence"
    password: "tpXAEpiO9J4w"

mdns:
  disabled: false

web_server:
  port: 80
  auth:
    username: admin
    password: !secret webserver_password
```

### Anything in the logs that might be useful for us?

```txt
I (243) esp_image: segment 4: paddr=000d1c70 vaddr=4038c6ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0xf (SPI_FAST_FLASH_BOOT)
Saved PC:0x40389a7e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5810,len:0x1684
load:0x403cc710,len:0x928
load:0x403ce710,len:0x2d7c
entry 0x403cc710
I (24) boot: ESP-IDF 4.4.5 2nd stage bootloader
I (24) boot: compile time 19:44:27
I (24) boot: chip revision: v0.4
I (26) boot.esp32c3: SPI Speed      : 80MHz
I (31) boot.esp32c3: SPI Mode       : DIO
I (36) boot.esp32c3: SPI Flash Size : 4MB
I (40) boot: Enabling RNG early entropy source...
I (46) boot: Partition Table:
I (49) boot: ## Label            Usage          Type ST Offset   Length
I (57) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (64) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (72) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (79) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (87) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (94) boot: End of partition table
I (98) esp_image: segment 0: paddr=00010020 vaddr=3c0a0020 size=21640h (136768) map
I (127) esp_image: segment 1: paddr=00031668 vaddr=3fc8f400 size=022e4h (  8932) load
I (129) esp_image: segment 2: paddr=00033954 vaddr=40380000 size=0c6c4h ( 50884) load
I (142) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=91c48h (597064) map
I (232) esp_image: segment 4: paddr=000d1c70 vaddr=4038c6c4 size=02c00h ( 11264) load
I (239) boot: Loaded app from partition at offset 0x10000
I (239) boot: Disabling RNG early entropy source...
I (241) cpu_start: Pro cpu up.
I (256) cpu_start: Pro cpu start user code
I (256) cpu_start: cpu freq: 160000000
I (256) cpu_start: Application information:
I (259) cpu_start: Project name:     esphome-presence
I (265) cpu_start: App version:      2023.8.3
I (270) cpu_start: Compile time:     Sep 18 2023 19:43:06
I (276) cpu_start: ELF file SHA256:  d2cfdb09122cfdde...
I (282) cpu_start: ESP-IDF:          4.4.5
I (287) cpu_start: Min chip rev:     v0.3
I (291) cpu_start: Max chip rev:     v0.99 
I (296) cpu_start: Chip rev:         v0.4
I (301) heap_init: Initializing. RAM available for dynamic allocation:
I (308) heap_init: At 3FC95940 len 00046DD0 (283 KiB): DRAM
I (314) heap_init: At 3FCDC710 len 00002950 (10 KiB): STACK/DRAM
I (321) heap_init: At 50000020 len 00001FE0 (7 KiB): RTCRAM
I (328) spi_flash: detected chip: generic
I (328) spi_flash: flash io: dio
I (329) sleep: Configure to isolate all GPIO pins in sleep state
I (334) sleep: Enable automatic switching of GPIO sleep configuration
I (341) cpu_start: Starting scheduler.
[I][logger:262]: Log initialized
[C][ota:469]: There have been 1 suspected unsuccessful boot attempts.
[D][esp32.preferences:114]: Saving 1 preferences to flash...
[D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[I][app:029]: Running through setup()...
[C][wifi:038]: Setting up WiFi...
[D][esp-idf:000]: I (488) pp: pp rom version: 9387209

[D][esp-idf:000]: I (489) net80211: net80211 rom version: 9387209

[D][esp-idf:000]: I (491) wifi:
[D][esp-idf:000]: wifi driver task: 3fca23fc, prio:23, stack:6656, core=0
[D][esp-idf:000]: 

[D][esp-idf:000]: I (491) system_api: Base MAC address is not set

[D][esp-idf:000]: I (492) system_api: read default base MAC address from EFUSE

[D][esp-idf:000]: I (493) wifi:
[D][esp-idf:000]: wifi firmware version: 0f80fa0
[D][esp-idf:000]: 

[D][esp-idf:000]: I (494) wifi:
[D][esp-idf:000]: wifi certification version: v7.0
[D][esp-idf:000]: 

[D][esp-idf:000]: I (495) wifi:
[D][esp-idf:000]: config NVS flash: enabled
[D][esp-idf:000]: 

[D][esp-idf:000]: I (495) wifi:
[D][esp-idf:000]: config nano formating: disabled
[D][esp-idf:000]: 

[D][esp-idf:000]: I (496) wifi:
[D][esp-idf:000]: Init data frame dynamic rx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (496) wifi:
[D][esp-idf:000]: Init management frame dynamic rx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (497) wifi:
[D][esp-idf:000]: Init management short buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (497) wifi:
[D][esp-idf:000]: Init dynamic tx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (497) wifi:
[D][esp-idf:000]: Init static tx FG buffer num: 2
[D][esp-idf:000]: 

[D][esp-idf:000]: I (498) wifi:
[D][esp-idf:000]: Init static rx buffer size: 1600
[D][esp-idf:000]: 

[D][esp-idf:000]: I (498) wifi:
[D][esp-idf:000]: Init static rx buffer num: 10
[D][esp-idf:000]: 

[D][esp-idf:000]: I (499) wifi:
[D][esp-idf:000]: Init dynamic rx buffer num: 32
[D][esp-idf:000]: 

[D][esp-idf:000]: I (500) wifi_init: rx ba win: 6

[D][esp-idf:000]: I (500) wifi_init: tcpip mbox: 32

[D][esp-idf:000]: I (501) wifi_init: udp mbox: 6

[D][esp-idf:000]: I (501) wifi_init: tcp mbox: 6

[D][esp-idf:000]: I (501) wifi_init: tcp tx win: 5744

[D][esp-idf:000]: I (501) wifi_init: tcp rx win: 5744

[D][esp-idf:000]: I (502) wifi_init: tcp mss: 1440

[D][esp-idf:000]: I (502) wifi_init: WiFi IRAM OP enabled

[D][esp-idf:000]: I (502) wifi_init: WiFi RX IRAM OP enabled

[C][wifi:048]: Starting WiFi...
[C][wifi:049]:   Local MAC: 64:E8:33:D7:6A:30
[D][esp-idf:000]: I (503) phy_init: phy_version 970,1856f88,May 10 2023,17:44:12

[D][esp-idf:000]: I (539) wifi:
[D][esp-idf:000]: mode : sta (64:e8:33:d7:6a:30)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (540) wifi:
[D][esp-idf:000]: enable tsf
[D][esp-idf:000]: 

[D][esp-idf:000]: I (541) wifi:
[D][esp-idf:000]: Set ps type: 1

[D][esp-idf:000]: 

[D][wifi:425]: Starting scan...
[D][esp-idf:000]: I (544) wifi:
[D][esp-idf:000]: Set ps type: 1

[D][esp-idf:000]: 

[D][wifi:440]: Found networks:
[I][wifi:484]: - 'SMITH_HA' [redacted]▂▄▆█
[D][wifi:485]:     Channel: 6
[D][wifi:486]:     RSSI: -82 dB
[D][wifi:489]: - [redacted] [redacted]▂▄▆█
[D][wifi:489]: - [redacted] [redacted]▂▄▆█
[D][wifi:489]: - [redacted] [redacted]▂▄▆█
[I][wifi:274]: WiFi Connecting to 'SMITH_HA'...
[D][esp-idf:000]: I (3237) wifi:
[D][esp-idf:000]: new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[D][esp-idf:000]: I (3864) wifi:
[D][esp-idf:000]: state: init -> auth (b0)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (4865) wifi:
[D][esp-idf:000]: state: auth -> init (200)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (4866) wifi:
[D][esp-idf:000]: new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[W][wifi_esp32:641]: Event: Disconnected ssid='SMITH_HA' bssid=[redacted] reason='Auth Expired'
[W][wifi:588]: Error while connecting to network.
[W][wifi:624]: Restarting WiFi adapter...
[D][esp-idf:000]: I (4880) wifi:
[D][esp-idf:000]: flush txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (4880) wifi:
[D][esp-idf:000]: stop sw txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (4881) wifi:
[D][esp-idf:000]: lmac stop hw txq
[D][esp-idf:000]: 

[I][wifi:274]: WiFi Connecting to 'SMITH_HA'...
[D][esp-idf:000]: I (4983) wifi:
[D][esp-idf:000]: mode : sta (64:e8:33:d7:6a:30)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (4984) wifi:
[D][esp-idf:000]: enable tsf
[D][esp-idf:000]: 

[D][esp-idf:000]: I (4987) wifi:
[D][esp-idf:000]: Set ps type: 1

[D][esp-idf:000]: 

[D][esp-idf:000]: I (5079) wifi:
[D][esp-idf:000]: new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[D][esp-idf:000]: I (5081) wifi:
[D][esp-idf:000]: state: init -> auth (b0)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (6082) wifi:
[D][esp-idf:000]: state: auth -> init (200)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (6083) wifi:
[D][esp-idf:000]: new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[W][wifi_esp32:641]: Event: Disconnected ssid='SMITH_HA' bssid=[redacted] reason='Auth Expired'
[W][wifi:588]: Error while connecting to network.
[W][wifi:624]: Restarting WiFi adapter...
[D][esp-idf:000]: I (6096) wifi:
[D][esp-idf:000]: flush txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (6096) wifi:
[D][esp-idf:000]: stop sw txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (6097) wifi:
[D][esp-idf:000]: lmac stop hw txq
[D][esp-idf:000]: 

[D][wifi:425]: Starting scan...
[D][esp-idf:000]: I (11199) wifi:
[D][esp-idf:000]: mode : sta (64:e8:33:d7:6a:30)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (11200) wifi:
[D][esp-idf:000]: enable tsf
[D][esp-idf:000]: 

[D][esp-idf:000]: I (11202) wifi:
[D][esp-idf:000]: Set ps type: 1

[D][esp-idf:000]: 

[D][wifi:440]: Found networks:
[I][wifi:484]: - 'SMITH_HA' [redacted]▂▄▆█
[D][wifi:485]:     Channel: 6
[D][wifi:486]:     RSSI: -84 dB
[D][wifi:489]: - [redacted] [redacted]▂▄▆█
[D][wifi:489]: - [redacted] [redacted]▂▄▆█
[D][wifi:489]: - [redacted] [redacted]▂▄▆█
[I][wifi:274]: WiFi Connecting to 'SMITH_HA'...
[D][esp-idf:000]: I (13881) wifi:
[D][esp-idf:000]: new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[D][esp-idf:000]: I (13882) wifi:
[D][esp-idf:000]: state: init -> auth (b0)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (14883) wifi:
[D][esp-idf:000]: state: auth -> init (200)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (14884) wifi:
[D][esp-idf:000]: new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[W][wifi_esp32:641]: Event: Disconnected ssid='SMITH_HA' bssid=[redacted] reason='Auth Expired'
[W][wifi:588]: Error while connecting to network.
[W][wifi:624]: Restarting WiFi adapter...
[D][esp-idf:000]: I (14898) wifi:
[D][esp-idf:000]: flush txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (14898) wifi:
[D][esp-idf:000]: stop sw txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (14899) wifi:
[D][esp-idf:000]: lmac stop hw txq
[D][esp-idf:000]: 

[I][wifi:274]: WiFi Connecting to 'SMITH_HA'...
[D][esp-idf:000]: I (15000) wifi:
[D][esp-idf:000]: mode : sta (64:e8:33:d7:6a:30)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (15001) wifi:
[D][esp-idf:000]: enable tsf
[D][esp-idf:000]: 

[D][esp-idf:000]: I (15004) wifi:
[D][esp-idf:000]: Set ps type: 1

[D][esp-idf:000]: 

[D][esp-idf:000]: I (15007) wifi:
[D][esp-idf:000]: new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[D][esp-idf:000]: I (15008) wifi:
[D][esp-idf:000]: state: init -> auth (b0)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (16009) wifi:
[D][esp-idf:000]: state: auth -> init (200)
[D][esp-idf:000]: 

[D][esp-idf:000]: I (16010) wifi:
[D][esp-idf:000]: new:<6,0>, old:<6,0>, ap:<255,255>, sta:<6,0>, prof:1
[D][esp-idf:000]: 

[W][wifi_esp32:641]: Event: Disconnected ssid='SMITH_HA' bssid=[redacted] reason='Auth Expired'
[W][wifi:588]: Error while connecting to network.
[W][wifi:624]: Restarting WiFi adapter...
[D][esp-idf:000]: I (16024) wifi:
[D][esp-idf:000]: flush txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (16024) wifi:
[D][esp-idf:000]: stop sw txq
[D][esp-idf:000]: 

[D][esp-idf:000]: I (16025) wifi:
[D][esp-idf:000]: lmac stop hw txq
[D][esp-idf:000]:
```

**Comment by HeMan** [comment] 2023-09-21 20:56
Do you happen to be using an Ubiquiti network? I've had similar problems with my network and ESPs.

**Comment by xdecock** [comment] 2023-09-25 17:33
Same here managed ro work around it by changing the power to 

```yaml
wifi:
  output_power: 8.5
```

**Comment by mclever** [comment] 2023-10-02 02:10
I'm seeing the same thing on my ESP-WROOM-32's after the most recent update. Even with a basic config it can't connect to WiFi with auth expired errors. 

Tried the output_power change and it didn't make a difference.

Going to try and revert to backup of esphone add-on and re-flash.

**Comment by aeonSolutions** [comment] 2023-12-17 12:07
I've came across the same problem when coding my ESP32 base libraries ( see here : https://github.com/aeonSolutions/aeonlabs-ESP32-C-Base-Firmware-Libraries )

You have to add this code after running WiFi.softAP or WiFi.begin for the Wifi to work.

WiFi.setTxPower(WIFI_POWER_8_5dBm); 

see https://www.wemos.cc/en/latest/tutorials/c3/get_started_with_arduino_c3.html#wifi

**Comment by ssieb** [comment] 2023-12-17 22:11
Isn't that the same as the `output_power:` option?

**Comment by rikki78** [comment] 2023-12-22 15:26
> I'm seeing the same thing on my ESP-WROOM-32's after the most recent update. Even with a basic config it can't connect to WiFi with auth expired errors.
> 
> Tried the output_power change and it didn't make a difference.
> 
> Going to try and revert to backup of esphone add-on and re-flash.

Did reverting make a difference?

**Comment by Particpant** [comment] 2024-01-07 00:39
I'm seeing an inability to connect from some brand new ESP-WROOM32 boards. Same WiFi AP (and config) is just fine with a bunch of sonoff 8266 devices that are on an older ESPHome.

**Comment by ThomDietrich** [comment] 2024-01-22 23:10
I can confirm this issue.
I am working with the Esp32-c3-supermini devboard and @HeMan I am indeed on a Ubiquiti Unifi network.

The issue was resolved via:

```yaml
wifi:
  output_power: 8.5
```

**Comment by clydebarrow** [comment] 2024-01-24 01:09
> I am working with the Esp32-c3-supermini

What colour is the antenna? I have two types of these, one works, one doesn't - seems to be that the antenna is useless.

Good one on the left (red antenna) bad on the right.

![PXL_20240122_235357978 MP](https://github.com/esphome/issues/assets/2366188/111c7c55-3b46-4f62-a8e8-12b9270919a6)

**Comment by ThomDietrich** [comment] 2024-01-24 01:13
> seems to be that the antenna is useless.

Actually I can confirm these are trash :-( Setting `output_power` did *something* but the node is constantly dropping from the network.

**Comment by nielsnl68** [comment] 2024-01-24 01:40
I did have the same issues with the Lolin D1 c3 mini. In the end i stopped using them.

**Comment by clydebarrow** [comment] 2024-01-24 02:03
> ```
> [D][wifi:485]:     Channel: 6
> [D][wifi:486]:     RSSI: -82 dB
> ```

There is a clue here. My good C3 reports -49dBm in the same location as the bad one reports -81. That's a huge difference.

**Comment by clydebarrow** [comment] 2024-01-24 03:07
Just for kicks I removed the antenna from the bad one and soldered a 1/2 wavelength piece of wire in its place. That brought the reported  RSSI up quite a bit (to -50 or so) but connections still fail.

![PXL_20240124_021215607 MP](https://github.com/esphome/issues/assets/2366188/a1f629dd-7f1c-472a-8c9d-2822f0c5b23b)

**Comment by ThomDietrich** [comment] 2024-01-24 09:52
Great initiative, sadly no success. I will show mine the way to the trash can.
Off topic but btw I am super happy with the "M5Stack M5Stamp C3U". Small form factor, a bit of eye candy, great wifi performance, and a company I deem supporting as they develop cool stuff. Only downside: $8 vs $3 per module

**Comment by clydebarrow** [comment] 2024-01-24 10:19
There's clearly something more than just a bad antenna going on. I have 7 and one of those will connect to WiFi but only with a strong signal, the rest never do. 

So unless there is anything new, this issue should be closed IMHO.

**Comment by jalr** [comment] 2024-02-21 15:13
I also tried @clydebarrow's modification, but in my case it made the problem worse and I ended up with no connection instead of a rare one like before.

I looked at the design of the filter on my board and it turns out that the LNA pin of the ESP is connected to a capacitor and one side of the chip antenna is then connected to the other side of that capacitor. I'm not that familiar with RF stuff, but this is different from the CLC circuit described in the [RF tuning section of the ESP Hardware Design Guidelines](https://docs.espressif.com/projects/esp-hardware-design-guidelines/en/latest/esp32c3/schematic-checklist.html#rf-tuning)

Thinking I could neglect the capacitance for now as these are quite low, I wrapped a botched 4 turn air coil around the antenna wire (~1.8mm diameter). I removed the capacitor and replaced it with the coil. Then, I scraped off the PCB to expose the ground and soldered the antenna wire shield there. The second pad of the chip antenna is not grounded!
I have used an antenna from a discarded wifi router and also tried a diy biquad antenna, and both work quite well.


![ESP32-C3_antenna_mod](https://github.com/esphome/issues/assets/8084342/b34feeda-ca51-4b4f-84ad-10fdb16aa389)

**Comment by malexmave** [comment] 2024-02-22 07:41
For me, when I have the exact same device and flash it from one of the pre-built binaries off the website (e.g., as a bluetooth proxy), it works fine. When I flash it using esphome in my HomeAssistant, it has the connection problems described here. So I doubt that this is a hardware issue, at least on my devices. I tried the software workarounds described here, and none of them seem to work for me. Is there a reason why so many people here seem to be sure that it is a hardware issue, and not a regression somewhere in the stack?

**Comment by aeonSolutions** [comment] 2024-02-26 10:43
> I also tried @clydebarrow's modification, but in my case it made the problem worse and I ended up with no connection instead of a rare one like before.
> 
> I looked at the design of the filter on my board and it turns out that the LNA pin of the ESP is connected to a capacitor and one side of the chip antenna is then connected to the other side of that capacitor. I'm not that familiar with RF stuff, but this is different from the CLC circuit described in the [RF tuning section of the ESP Hardware Design Guidelines](https://docs.espressif.com/projects/esp-hardware-design-guidelines/en/latest/esp32c3/schematic-checklist.html#rf-tuning)
> 
> Thinking I could neglect the capacitance for now as these are quite low, I wrapped a botched 4 turn air coil around the antenna wire (~1.8mm diameter). I removed the capacitor and replaced it with the coil. Then, I scraped off the PCB to expose the ground and soldered the antenna wire shield there. The second pad of the chip antenna is not grounded! I have used an antenna from a discarded wifi router and also tried a diy biquad antenna, and both work quite well.
> 
> ![ESP32-C3_antenna_mod](https://private-user-images.githubusercontent.com/8084342/306661573-b34feeda-ca51-4b4f-84ad-10fdb16aa389.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDQzMjksIm5iZiI6MTcwODk0NDAyOSwicGF0aCI6Ii84MDg0MzQyLzMwNjY2MTU3My1iMzRmZWVkYS1jYTUxLTRiNGYtODRhZC0xMGZkYjE2YWEzODkuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjZUMTA0MDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzczMjFkMDM1OGNmZTgxYzM2MDRlYjNmMzhkYzA1MzJkOWI2NzY4N2U5MjU1NGJlMWU4NWIzN2JlODdjYzg5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o8J6E9iHNcxPwsjcIlWbGaDu1U2i3VwIl1pLRVWERlU)

if your board is using an onboard antenna the layout is correct as it is . 
If you're using an external antenna connected to a IPEX connector the CLC circuit is recommended but not mandatory.

**Comment by Gelisob** [comment] 2024-03-12 17:40
Can confirm same issue with latest (at the time of posting) ESPHOME and this esp32 c3 supermini with black ceramic antenna.
I got them with idea to replace ceramic with wired pcb antenna but was curious to check signal dBm difference before changing.
It kept failing with auth expired and other messages when having original black antenna. Closer to router with stronger signal after much spamming got in. I kept looking at numbers in esphome terminal so I could see what wifi networks and with what strength it saw all the time. Then I changed to pcb antenna and esp immediately saw more networks and dBm to my wifi went from -70 to -45. But now it never was able to join. So there must be something more going on with those black ceramic antenna units. Avoid until resolved. 

Same sketch onto red antenna esp32 c3 and instantly joined, no issues. 

Tried removing capacitor like @jalr did and actually soldering ground plane into ground i cleaned but no help. Do not know enough about antennas probably. But i'm quite sure that if i make this antenna change on red one - it will continue working normally.
![430495350_280875311711897_4408190967217207190_n](https://github.com/esphome/issues/assets/22873920/bd0ce69d-a6f1-4f7f-9e8c-2fe5384a6cda)
![430414221_374605855463158_3562827963566906622_n](https://github.com/esphome/issues/assets/22873920/fd4c55db-f9da-47a7-86fb-71c53ad5f051)

**Comment by HeMan** [comment] 2024-03-12 18:04
Can you people confirm that you are not running Ubiquiti networks?

**Comment by clydebarrow** [comment] 2024-03-12 18:53
> Can you people confirm that you are not running Ubiquiti networks?

I cannot confirm that - i.e. I am using Ubiquiti. And I agree with the other comments that there is more to it than just antenna/signal strength. Any chance the chips are non-genuine?

**Comment by HeMan** [comment] 2024-03-12 19:30
The reason I asked is that I think it some kind of Ubiquiti-issue. I have a few different ESPs of varying types that have been working perfect for some years that suddenly got `Disconnected reason='Auth Expired'` with no change. They started working some days later and been working since.

**Comment by rikki78** [comment] 2024-03-12 19:54
I'm not using Ubiquiti and have the same issue.

**Comment by Gelisob** [comment] 2024-03-12 20:03
> Can you people confirm that you are not running Ubiquiti networks?

i'm not sure what you mean by that. Some specific network type? 
Mine is just common Telia home internet, hosted by an asus wifi router. 
And keep in mind, same sketch/location/network - red antenna unit - all works. This alone should be clear sign that it's some hardware issue. Add to that the fact, that from terminal I can see that it scans for networks and antenna change does change it's coverage and signal strengths.

**Comment by ThomDietrich** [comment] 2024-03-12 22:29
@HeMan I own a Ubiquiti Unifi wifi network but I think it is pretty clear by now that this is a simple bad hardware issue.

**Comment by HeMan** [comment] 2024-03-13 05:51
> @HeMan I own a Ubiquiti Unifi wifi network but I think it is pretty clear by now that this is a simple bad hardware issue.

Yes, it's pretty clear that I was barking up the wrong tree.

**Comment by randybb** [comment] 2024-03-13 08:37
Such problem on "Ubiquity" is only when people have no clue what they are doing and enable "Band Steering" for 2.4 GHz only devices. So please, don't blame Ubiquity :)

**Comment by Gelisob** [comment] 2024-03-13 11:31
maybe we can discuss what the hardware issue could be instead. Because - the device does see networks and tries connecting. Does esp32 have some even more core level firmware that uploading esphome sketch does not change, that we could flash over? Bootloader or something.. to take from "red" and put on "black" ?

**Comment by malexmave** [comment] 2024-03-13 12:41
Do all of you have the same issues when you flash a [pre-built ESPHome project](https://esphome.io/projects/) for something like a bluetooth proxy? Because, for me, the same device works with a pre-built image, but fails with the errors described here when compiling it myself.

**Comment by clydebarrow** [comment] 2024-03-13 21:05
> Do all of you have the same issues when you flash a [pre-built ESPHome project](https://esphome.io/projects/) for something like a bluetooth proxy?

Yes.

So, since this is clearly a hardware problem, not an ESPHome software problem, I'm closing this issue. Comments can still be added if there is any new information.

**Closed by clydebarrow** 2024-03-13 21:05 UTC
