### ISSUE TITLE
Update of esphome with raspberry pi picofails.

### ISSUE THREAD

**Issue by marjaco** [esphome/issues#5295] opened 2023-12-26 09:25 UTC
### The problem

Updating my Raspberyy Pi Pico since esphome version 2023.12.1 fails with: 
(see below, logfile)
This is the log that I get updating. All above seems fine with no warnings or error messages. 

### Which version of ESPHome has the issue?

2023.12.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

RP2040

### Board

Raspberyy Pi Pico

### Component causing the issue

Update/Install of firmware.elf

### Anything in the logs that might be useful for us?

```txt
/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/10.3.0/../../../../arm-none-eabi/bin/ld: unrecognized option '--no-warn-rwx-segments'

/data/cache/platformio/packages/toolchain-rp2040-earlephilhower/bin/../lib/gcc/arm-none-eabi/10.3.0/../../../../arm-none-eabi/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status

*** [.pioenvs/bettlampe/firmware.elf] Error 1
```

**Comment by ssieb** [comment] 2023-12-26 09:33
Duplicate of https://github.com/esphome/issues/issues/5262

**Closed by ssieb** 2023-12-26 09:33 UTC
