### ISSUE TITLE
Platformio Problem

### ISSUE THREAD

**Issue by Ozanelon** [esphome/issues#4979] opened 2023-10-13 20:57 UTC
### The problem

Hello, I'm new to esphome. I just uploaded my first code but I got this error. I tried it on other devices but it didn't work. It is always  getting stuck here. 

![Screenshot_3](https://github.com/esphome/issues/assets/67023010/1e5e5f4b-9eb2-482a-9b3e-80dbe05684c0)

### Which version of ESPHome has the issue?

2023.11.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Supervisor 2023.10.0 - Operating System 11.0

### What platform are you using?

ESP8266

### Board

Nodemcu ver. 2

### Component causing the issue

platformio

**Comment by ssieb** [comment] 2023-10-13 21:48
Duplicate of https://github.com/esphome/issues/issues/4894

**Closed by ssieb** 2023-10-13 21:48 UTC
