### ISSUE TITLE
`partition` light creates a ghost entity in HA

### ISSUE THREAD

**Issue by nagyrobi** [esphome/issues#2959] opened 2022-01-19 10:48 UTC
### The problem

I added a `partition` type light to my config, based on `single_light_id` segments like below.

The problem is that in HA, along with the expected `light.vbar_ossz` entity, another one ghostly appeared: `light.esphome_szines_dmxlight` which is not configured anywhere, to be created.

It disappears if I remove the partition light from config, it appears back when I re-add it.

The friendly name of this strange entity is empty string. Looks like the `entity_id` is composed of `light.esphome_` + name of node + `light`.

![kép](https://user-images.githubusercontent.com/1550668/150112755-4f2b13b1-32ed-4370-baa6-92fc45febca1.png)

It looks like it acts only on the first light, with id `dmx_bar_1`

The orginal entities of the lights and the partition light entitiy are all functioning normally, this extra one appears from nowhere, what's the reason?

### Which version of ESPHome has the issue?

v2022.1.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.12.10

### What platform are you using?

ESP8266

### Board

Wemos D1

### Component causing the issue

partition light

### Example YAML snippet

```yaml
light:
- platform: rgbw
  name: "VBar1"
  id: dmx_bar_1
  red: vbar1_red
  green: vbar1_green
  blue: vbar1_blue
  white: vbar1_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: rgbw
  name: "VBar2"
  id: dmx_bar_2
  red: vbar2_red
  green: vbar2_green
  blue: vbar2_blue
  white: vbar2_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: rgbw
  name: "VBar3"
  id: dmx_bar_3
  red: vbar3_red
  green: vbar3_green
  blue: vbar3_blue
  white: vbar3_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: rgbw
  name: "VBar4"
  id: dmx_bar_4
  red: vbar4_red
  green: vbar4_green
  blue: vbar4_blue
  white: vbar4_amber
  icon: mdi:spotlight
  default_transition_length: 0s
  color_interlock: false
  restore_mode: RESTORE_DEFAULT_ON

- platform: partition
  name: "VBar össz"
  default_transition_length: 0s
  restore_mode: RESTORE_DEFAULT_OFF
  segments:
    - single_light_id: dmx_bar_1
    - single_light_id: dmx_bar_2
    - single_light_id: dmx_bar_3
    - single_light_id: dmx_bar_4
  effects:
    - addressable_rainbow:
    - addressable_color_wipe:
```

### Anything in the logs that might be useful for us?

```txt
2022-01-19 12:01:14 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID szines-dmxlight already exists - ignoring light.esphome_szines_dmxlight
2022-01-19 12:01:14 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID szines-dmxlight already exists - ignoring light.esphome_szines_dmxlight
2022-01-19 12:01:14 ERROR (MainThread) [homeassistant.components.light] Platform esphome does not generate unique IDs. ID szines-dmxlight already exists - ignoring light.esphome_szines_dmxlight

```

### Additional information

Attributes of the ghost entity:
```
supported_color_modes:
  - rgbw
friendly_name: ''
supported_features: 40
```

**Comment by jenscski** [comment] 2022-01-19 12:29
Looks like you want the four rgbw leds to be only used throug the partition?

How about adding `internal: true` to the four of them?

**Comment by nagyrobi** [comment] 2022-01-19 12:36
Nope. I want them separately too. The ghost entity is created **in addition** to the _original light_ and the _partition_.

**Comment by jenscski** [comment] 2022-01-20 08:57
Do you see anything in the log from the ESPHome unit about this entity, or is it only found in HA?

**Comment by nagyrobi** [comment] 2022-01-20 10:59
ESPHome Log:
```
[11:56:44][I][app:102]: ESPHome version 2022.1.1 compiled on Jan 20 2022, 11:49:40
[11:56:44][C][wifi:488]: WiFi:
[11:56:44][C][wifi:350]:   Local MAC: E8:DB:84:D0:41:C8
[11:56:44][C][wifi:351]:   SSID: [redacted]
[11:56:44][C][wifi:352]:   IP Address: 172.22.215.52
[11:56:44][C][wifi:354]:   BSSID: [redacted]
[11:56:44][C][wifi:355]:   Hostname: 'szines-dmx'
[11:56:44][C][wifi:357]:   Signal strength: -52 dB ▂▄▆█
[11:56:44][C][wifi:361]:   Channel: 11
[11:56:44][C][wifi:362]:   Subnet: 255.255.255.0
[11:56:44][C][wifi:363]:   Gateway: 172.22.215.254
[11:56:44][C][wifi:364]:   DNS1: 0.0.0.0
[11:56:44][C][wifi:365]:   DNS2: 0.0.0.0
[11:56:44][C][logger:233]: Logger:
[11:56:44][C][logger:234]:   Level: DEBUG
[11:56:44][C][logger:235]:   Log Baud Rate: 0
[11:56:44][C][logger:236]:   Hardware UART: UART0
[11:56:44][D][dmx512:015]: update
[11:56:44][C][uart.arduino_esp8266:100]: UART Bus:
[11:56:44][C][uart.arduino_esp8266:101]:   TX Pin: GPIO2
[11:56:44][C][uart.arduino_esp8266:106]:   Baud Rate: 250000 baud
[11:56:44][C][uart.arduino_esp8266:107]:   Data Bits: 8
[11:56:44][C][uart.arduino_esp8266:108]:   Parity: NONE
[11:56:44][C][uart.arduino_esp8266:109]:   Stop bits: 2
[11:56:44][C][uart.arduino_esp8266:111]:   Using hardware serial interface.
[11:56:44][C][dmx512:026]: Setting up DMX512...
[11:56:44][C][switch.gpio:048]: GPIO Switch 'DMX vezérlő MUTE'
[11:56:44][C][switch.gpio:048]:   Icon: 'mdi:lightbulb-off'
[11:56:44][C][switch.gpio:049]:   Pin: GPIO13
[11:56:44][C][switch.gpio:071]:   Restore Mode: Always OFF
[11:56:44][C][uptime.sensor:031]: Uptime Sensor 'DMX vezérlő uptime'
[11:56:44][C][uptime.sensor:031]:   State Class: 'total_increasing'
[11:56:44][C][uptime.sensor:031]:   Unit of Measurement: 's'
[11:56:44][C][uptime.sensor:031]:   Accuracy Decimals: 0
[11:56:44][C][uptime.sensor:031]:   Icon: 'mdi:timer-outline'
[11:56:44][C][template.number:049]: Template Number 'VBar1 Effect Level'
[11:56:44][C][template.number:049]:   Icon: 'mdi:flower-pollen-outline'
[11:56:44][C][template.number:050]:   Optimistic: YES
[11:56:44][C][template.number:051]:   Update Interval: 60.0s
[11:56:44][C][template.number:049]: Template Number 'VBar2 Effect Level'
[11:56:44][C][template.number:049]:   Icon: 'mdi:flower-pollen-outline'
[11:56:44][C][template.number:050]:   Optimistic: YES
[11:56:44][C][template.number:051]:   Update Interval: 60.0s
[11:56:44][C][template.number:049]: Template Number 'VBar3 Effect Level'
[11:56:44][C][template.number:049]:   Icon: 'mdi:flower-pollen-outline'
[11:56:44][C][template.number:050]:   Optimistic: YES
[11:56:44][C][template.number:051]:   Update Interval: 60.0s
[11:56:44][C][template.number:049]: Template Number 'VBar4 Effect Level'
[11:56:44][C][template.number:049]:   Icon: 'mdi:flower-pollen-outline'
[11:56:44][C][template.number:050]:   Optimistic: YES
[11:56:44][C][template.number:051]:   Update Interval: 60.0s
[11:56:44][C][template.select:064]: Template Select 'VBar1 Effect'
[11:56:44][C][template.select:064]:   Icon: 'mdi:pan'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: None
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][template.select:064]: Template Select 'VBar1 Effect Mode'
[11:56:44][C][template.select:064]:   Icon: 'mdi:dots-hexagon'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: Change-Fade-Sound-1-Macro-OFF
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][template.select:064]: Template Select 'VBar2 Effect'
[11:56:44][C][template.select:064]:   Icon: 'mdi:pan'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: None
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][template.select:064]: Template Select 'VBar2 Effect Mode'
[11:56:44][C][template.select:064]:   Icon: 'mdi:dots-hexagon'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: Change-Fade-Sound-1-Macro-OFF
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][template.select:064]: Template Select 'VBar3 Effect'
[11:56:44][C][template.select:064]:   Icon: 'mdi:pan'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: None
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][template.select:064]: Template Select 'VBar3 Effect Mode'
[11:56:44][C][template.select:064]:   Icon: 'mdi:dots-hexagon'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: Change-Fade-Sound-1-Macro-OFF
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][template.select:064]: Template Select 'VBar4 Effect'
[11:56:44][C][template.select:064]:   Icon: 'mdi:pan'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: None
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][template.select:064]: Template Select 'VBar4 Effect Mode'
[11:56:44][C][template.select:064]:   Icon: 'mdi:dots-hexagon'
[11:56:44][C][template.select:065]:   Update Interval: 60.0s
[11:56:44][C][template.select:068]:   Optimistic: YES
[11:56:44][C][template.select:069]:   Initial Option: Change-Fade-Sound-1-Macro-OFF
[11:56:44][C][template.select:070]:   Restore Value: YES
[11:56:44][C][light:098]: Light 'VBar1'
[11:56:44][C][light:100]:   Default Transition Length: 0.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light 'VBar1 Dimmer'
[11:56:44][C][light:100]:   Default Transition Length: 2.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light 'VBar2'
[11:56:44][C][light:100]:   Default Transition Length: 0.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light 'VBar2 Dimmer'
[11:56:44][C][light:100]:   Default Transition Length: 2.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light 'VBar3'
[11:56:44][C][light:100]:   Default Transition Length: 0.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light 'VBar3 Dimmer'
[11:56:44][C][light:100]:   Default Transition Length: 2.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light 'VBar4'
[11:56:44][C][light:100]:   Default Transition Length: 0.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light 'VBar4 Dimmer'
[11:56:44][C][light:100]:   Default Transition Length: 2.0s
[11:56:44][C][light:101]:   Gamma Correct: 2.80
[11:56:44][C][light:098]: Light ''
[11:56:44][C][light:100]:   Default Transition Length: 0.0s
[11:56:44][C][light:101]:   Gamma Correct: 0.00
[11:56:44][C][light:098]: Light ''
[11:56:44][C][light:100]:   Default Transition Length: 0.0s
[11:56:44][C][light:101]:   Gamma Correct: 0.00
[11:56:44][C][light:098]: Light ''
[11:56:44][C][light:100]:   Default Transition Length: 0.0s
[11:56:44][C][light:101]:   Gamma Correct: 0.00
[11:56:44][C][light:098]: Light ''
[11:56:45][C][light:100]:   Default Transition Length: 0.0s
[11:56:45][C][light:101]:   Gamma Correct: 0.00
[11:56:45][C][light:098]: Light 'VBar össz'
[11:56:45][C][light:100]:   Default Transition Length: 0.0s
[11:56:45][C][light:101]:   Gamma Correct: 2.80
[11:56:45][C][restart.button:017]: Restart Button 'DMX vezérlő újraindítás'
[11:56:45][C][status:034]: Status Binary Sensor 'DMX vezérlő hálózat'
[11:56:45][C][status:034]:   Device Class: 'connectivity'
[11:56:45][C][ota:082]: Over-The-Air Updates:
[11:56:45][C][ota:083]:   Address: 172.22.215.52:8266
[11:56:45][C][ota:086]:   Using Password.
[11:56:45][C][api:134]: API Server:
[11:56:45][C][api:135]:   Address: 172.22.215.52:6053
[11:56:45][C][api:137]:   Using noise encryption: YES
[11:56:45][C][wifi_signal.sensor:009]: WiFi Signal 'DMX vezérlő WiFi jelerősség'
[11:56:45][C][wifi_signal.sensor:009]:   Device Class: 'signal_strength'
[11:56:45][C][wifi_signal.sensor:009]:   State Class: 'measurement'
[11:56:45][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dBm'
[11:56:45][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[11:56:45][C][mdns:084]: mDNS:
[11:56:45][C][mdns:085]:   Hostname: szines-dmx
```

Looks like it errorneously tries to create 4 additional lights with empty names.

**Comment by jenscski** [comment] 2022-01-20 11:05
Yes, looks like it. I have no idea why, but what I would have done, is removing everything, and adding one thing (or group of things) at at a time to see what triggers thoose lights, just to narrow down what part generates theese lights.

**Comment by nagyrobi** [comment] 2022-01-20 12:03
As I wrote in the first message - the problem only appears when I add the partition light.

**Comment by jenscski** [comment] 2022-01-20 12:10
Ah, sorry about that ..

Have you examined the contents of the generated main.cpp file?
Those lights should probablye be declared in that file, perhaps you get a clue about what generates them.

**Comment by OttoWinter** [comment] 2022-01-20 12:34
Duplicate of https://github.com/esphome/issues/issues/2835

**Closed by OttoWinter** 2022-01-20 12:34 UTC
Labels: integration: partition
