### ISSUE TITLE
Extreme pulse_meter readings and swings

### ISSUE THREAD

**Issue by emeyedeejay** [esphome/issues#3763] opened 2022-11-04 20:15 UTC
### Which version of ESPHome has the issue?

[I][app:102]: ESPHome version 2022.10.2 compiled on Nov  4 2022

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2022.10.5 Supervisor 2022.10.2 Operating System 9.3 Frontend 20221010.0 - latest

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

sensor:    # Pulse meter   - platform: pulse_meter

### The problem
An existing pulse_meter setup has been running well for months but recently started behaving very weirdly. The readings will swing from e.g. 1000W to like 36 000 000W and back again.

I cannot recall making any changes to the setup but is it possible a recent update broke something?

My config:

```
sensor:    # Pulse meter
  - platform: pulse_meter
    name: 'Current Power Consumption'
    id: sensor_current_power_consumption
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: D2
    internal_filter_mode: pulse
    filters:
  # multiply value = (60 / imp value) * 1000
  # - multiply: 60
    - lambda: return x * ((60.0 / 1000) * 1000.0);
```

![221101224235-Sharex screenshot](https://user-images.githubusercontent.com/8543879/199337382-5460fd8a-e6e7-43ae-80be-867377333a07.gif)

Looks like it went nuts on 24 October - doe that match any release date maybe?

![image](https://user-images.githubusercontent.com/8543879/199342106-9b5b2a5e-990b-4af6-8fda-a2a07a232458.png)

Some log output:

```
INFO Reading configuration /config/esphome/electricity-usage-monitor.yaml...
INFO Detected timezone 'Africa/Johannesburg'
INFO Starting log output from electricity-usage-monitor.local using esphome API
INFO Successfully connected to electricity-usage-monitor.local
[22:42:52][I][app:102]: ESPHome version 2022.10.1 compiled on Oct 26 2022, 12:16:53
[22:42:52][C][wifi:502]: WiFi:
[22:42:52][C][wifi:360]:   Local MAC: B4:E6:2D:13:F0:A9
[22:42:52][C][wifi:361]:   SSID: 'JNET'[redacted]
[22:42:52][C][wifi:362]:   IP Address: 192.168.0.120
[22:42:52][C][wifi:363]:   BSSID: 78:8A:20:F7:3B:46[redacted]
[22:42:52][C][wifi:365]:   Hostname: 'electricity-usage-monitor'
[22:42:52][C][wifi:367]:   Signal strength: -71 dB ▂▄▆█
[22:42:52][C][wifi:371]:   Channel: 6
[22:42:52][C][wifi:372]:   Subnet: 255.255.255.0
[22:42:52][C][wifi:373]:   Gateway: 192.168.0.1
[22:42:52][C][wifi:374]:   DNS1: 192.168.0.1
[22:42:52][C][wifi:375]:   DNS2: 0.0.0.0
[22:42:52][C][logger:275]: Logger:
[22:42:52][C][logger:276]:   Level: DEBUG
[22:42:52][C][logger:277]:   Log Baud Rate: 115200
[22:42:52][C][logger:278]:   Hardware UART: UART0
[22:42:52][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Home power monitor'
[22:42:52][C][gpio.binary_sensor:016]:   Pin: GPIO4
[22:42:52][C][pulse_meter:069]: Pulse Meter 'Current Power Consumption'
[22:42:52][C][pulse_meter:069]:   Device Class: 'power'
[22:42:52][C][pulse_meter:069]:   State Class: 'measurement'
[22:42:52][C][pulse_meter:069]:   Unit of Measurement: 'W'
[22:42:52][C][pulse_meter:069]:   Accuracy Decimals: 0
[22:42:52][C][pulse_meter:069]:   Icon: 'mdi:flash-outline'
[22:42:52][C][pulse_meter:070]:   Pin: GPIO4
[22:42:52][C][pulse_meter:074]:   Filtering pulses shorter than 13 µs
[22:42:52][C][pulse_meter:076]:   Assuming 0 pulses/min after not receiving a pulse for 300s
[22:42:52][C][total_daily_energy:023]: Total Daily Energy 'Home daily power'
[22:42:52][C][total_daily_energy:023]:   Device Class: 'energy'
[22:42:52][C][total_daily_energy:023]:   State Class: 'total_increasing'
[22:42:52][C][total_daily_energy:023]:   Unit of Measurement: 'kWh'
[22:42:52][C][total_daily_energy:023]:   Accuracy Decimals: 3
[22:42:52][C][total_daily_energy:023]:   Icon: 'mdi:circle-slice-3'
[22:42:52][C][homeassistant.time:010]: Home Assistant Time:
[22:42:52][C][homeassistant.time:011]:   Timezone: 'SAST-2'
[22:42:52][C][captive_portal:088]: Captive Portal:
[22:42:52][C][mdns:100]: mDNS:
[22:42:52][C][mdns:101]:   Hostname: electricity-usage-monitor
[22:42:53][C][ota:089]: Over-The-Air Updates:
[22:42:53][C][ota:090]:   Address: electricity-usage-monitor.local:8266
[22:42:53][C][api:138]: API Server:
[22:42:53][C][api:139]:   Address: electricity-usage-monitor.local:6053
[22:42:53][C][api:143]:   Using noise encryption: NO
[22:42:54][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:42:57][D][sensor:126]: 'Home total power': Sending state 128.32300 kWh with 3 decimals of accuracy
[22:42:58][D][sensor:126]: 'Home total power': Sending state 128.32600 kWh with 3 decimals of accuracy
[22:42:58][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:42:59][D][sensor:126]: 'Current Power Consumption': Sending state 1474.80542 W with 0 decimals of accuracy
[22:42:59][D][sensor:126]: 'Home daily power': Sending state 1732.92236 kWh with 3 decimals of accuracy
[22:42:59][D][sensor:126]: 'Home total power': Sending state 128.32700 kWh with 3 decimals of accuracy
[22:42:59][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:02][D][sensor:126]: 'Current Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home daily power': Sending state 1732.92236 kWh with 3 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home total power': Sending state 128.33099 kWh with 3 decimals of accuracy
[22:43:02][D][sensor:126]: 'Current Power Consumption': Sending state 225000.00000 W with 0 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home daily power': Sending state 1732.92456 kWh with 3 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home total power': Sending state 128.33200 kWh with 3 decimals of accuracy
[22:43:02][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:04][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:07][D][sensor:126]: 'Current Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
[22:43:07][D][sensor:126]: 'Home daily power': Sending state 1732.92456 kWh with 3 decimals of accuracy
[22:43:07][D][sensor:126]: 'Home total power': Sending state 128.33600 kWh with 3 decimals of accuracy
[22:43:07][D][sensor:126]: 'Home total power': Sending state 128.33701 kWh with 3 decimals of accuracy
[22:43:07][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:09][D][sensor:126]: 'Current Power Consumption': Sending state 1449.85913 W with 0 decimals of accuracy
[22:43:09][D][sensor:126]: 'Home daily power': Sending state 1732.92554 kWh with 3 decimals of accuracy
[22:43:09][D][sensor:126]: 'Home total power': Sending state 128.33800 kWh with 3 decimals of accuracy
[22:43:09][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:12][D][sensor:126]: 'Current Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
[22:43:12][D][sensor:126]: 'Home daily power': Sending state 1732.92554 kWh with 3 decimals of accuracy
[22:43:12][D][sensor:126]: 'Home total power': Sending state 128.34399 kWh with 3 decimals of accuracy
[22:43:12][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:14][D][sensor:126]: 'Home total power': Sending state 128.34599 kWh with 3 decimals of accuracy
[22:43:14][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:17][D][sensor:126]: 'Current Power Consumption': Sending state 1401.86914 W with 0 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home daily power': Sending state 1732.92761 kWh with 3 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home total power': Sending state 128.34801 kWh with 3 decimals of accuracy
[22:43:17][D][sensor:126]: 'Current Power Consumption': Sending state 240000.00000 W with 0 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home daily power': Sending state 1732.92993 kWh with 3 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home total power': Sending state 128.34900 kWh with 3 decimals of accuracy
[22:43:17][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:19][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:22][D][sensor:126]: 'Current Power Consumption': Sending state 257142.85938 W with 0 decimals of accuracy
[22:43:22][D][sensor:126]: 'Home daily power': Sending state 1733.29260 kWh with 3 decimals of accuracy
[22:43:22][D][sensor:126]: 'Home total power': Sending state 128.35500 kWh with 3 decimals of accuracy
[22:43:22][D][sensor:126]: 'Current Power Consumption': Sending state 3600000.00000 W with 0 decimals of accuracy

```

### Example YAML snippet

```yaml
sensor:    # Pulse meter
  - platform: pulse_meter
    name: 'Current Power Consumption'
    id: sensor_current_power_consumption
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: D2
    internal_filter_mode: pulse
    filters:
  # multiply value = (60 / imp value) * 1000
  # - multiply: 60
    - lambda: return x * ((60.0 / 1000) * 1000.0);
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/electricity-usage-monitor.yaml...
INFO Detected timezone 'Africa/Johannesburg'
INFO Starting log output from electricity-usage-monitor.local using esphome API
INFO Successfully connected to electricity-usage-monitor.local
[22:42:52][I][app:102]: ESPHome version 2022.10.1 compiled on Oct 26 2022, 12:16:53
[22:42:52][C][wifi:502]: WiFi:
[22:42:52][C][wifi:360]:   Local MAC: B4:E6:2D:13:F0:A9
[22:42:52][C][wifi:361]:   SSID: 'JNET'[redacted]
[22:42:52][C][wifi:362]:   IP Address: 192.168.0.120
[22:42:52][C][wifi:363]:   BSSID: 78:8A:20:F7:3B:46[redacted]
[22:42:52][C][wifi:365]:   Hostname: 'electricity-usage-monitor'
[22:42:52][C][wifi:367]:   Signal strength: -71 dB ▂▄▆█
[22:42:52][C][wifi:371]:   Channel: 6
[22:42:52][C][wifi:372]:   Subnet: 255.255.255.0
[22:42:52][C][wifi:373]:   Gateway: 192.168.0.1
[22:42:52][C][wifi:374]:   DNS1: 192.168.0.1
[22:42:52][C][wifi:375]:   DNS2: 0.0.0.0
[22:42:52][C][logger:275]: Logger:
[22:42:52][C][logger:276]:   Level: DEBUG
[22:42:52][C][logger:277]:   Log Baud Rate: 115200
[22:42:52][C][logger:278]:   Hardware UART: UART0
[22:42:52][C][gpio.binary_sensor:015]: GPIO Binary Sensor 'Home power monitor'
[22:42:52][C][gpio.binary_sensor:016]:   Pin: GPIO4
[22:42:52][C][pulse_meter:069]: Pulse Meter 'Current Power Consumption'
[22:42:52][C][pulse_meter:069]:   Device Class: 'power'
[22:42:52][C][pulse_meter:069]:   State Class: 'measurement'
[22:42:52][C][pulse_meter:069]:   Unit of Measurement: 'W'
[22:42:52][C][pulse_meter:069]:   Accuracy Decimals: 0
[22:42:52][C][pulse_meter:069]:   Icon: 'mdi:flash-outline'
[22:42:52][C][pulse_meter:070]:   Pin: GPIO4
[22:42:52][C][pulse_meter:074]:   Filtering pulses shorter than 13 µs
[22:42:52][C][pulse_meter:076]:   Assuming 0 pulses/min after not receiving a pulse for 300s
[22:42:52][C][total_daily_energy:023]: Total Daily Energy 'Home daily power'
[22:42:52][C][total_daily_energy:023]:   Device Class: 'energy'
[22:42:52][C][total_daily_energy:023]:   State Class: 'total_increasing'
[22:42:52][C][total_daily_energy:023]:   Unit of Measurement: 'kWh'
[22:42:52][C][total_daily_energy:023]:   Accuracy Decimals: 3
[22:42:52][C][total_daily_energy:023]:   Icon: 'mdi:circle-slice-3'
[22:42:52][C][homeassistant.time:010]: Home Assistant Time:
[22:42:52][C][homeassistant.time:011]:   Timezone: 'SAST-2'
[22:42:52][C][captive_portal:088]: Captive Portal:
[22:42:52][C][mdns:100]: mDNS:
[22:42:52][C][mdns:101]:   Hostname: electricity-usage-monitor
[22:42:53][C][ota:089]: Over-The-Air Updates:
[22:42:53][C][ota:090]:   Address: electricity-usage-monitor.local:8266
[22:42:53][C][api:138]: API Server:
[22:42:53][C][api:139]:   Address: electricity-usage-monitor.local:6053
[22:42:53][C][api:143]:   Using noise encryption: NO
[22:42:54][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:42:57][D][sensor:126]: 'Home total power': Sending state 128.32300 kWh with 3 decimals of accuracy
[22:42:58][D][sensor:126]: 'Home total power': Sending state 128.32600 kWh with 3 decimals of accuracy
[22:42:58][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:42:59][D][sensor:126]: 'Current Power Consumption': Sending state 1474.80542 W with 0 decimals of accuracy
[22:42:59][D][sensor:126]: 'Home daily power': Sending state 1732.92236 kWh with 3 decimals of accuracy
[22:42:59][D][sensor:126]: 'Home total power': Sending state 128.32700 kWh with 3 decimals of accuracy
[22:42:59][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:02][D][sensor:126]: 'Current Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home daily power': Sending state 1732.92236 kWh with 3 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home total power': Sending state 128.33099 kWh with 3 decimals of accuracy
[22:43:02][D][sensor:126]: 'Current Power Consumption': Sending state 225000.00000 W with 0 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home daily power': Sending state 1732.92456 kWh with 3 decimals of accuracy
[22:43:02][D][sensor:126]: 'Home total power': Sending state 128.33200 kWh with 3 decimals of accuracy
[22:43:02][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:04][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:07][D][sensor:126]: 'Current Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
[22:43:07][D][sensor:126]: 'Home daily power': Sending state 1732.92456 kWh with 3 decimals of accuracy
[22:43:07][D][sensor:126]: 'Home total power': Sending state 128.33600 kWh with 3 decimals of accuracy
[22:43:07][D][sensor:126]: 'Home total power': Sending state 128.33701 kWh with 3 decimals of accuracy
[22:43:07][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:09][D][sensor:126]: 'Current Power Consumption': Sending state 1449.85913 W with 0 decimals of accuracy
[22:43:09][D][sensor:126]: 'Home daily power': Sending state 1732.92554 kWh with 3 decimals of accuracy
[22:43:09][D][sensor:126]: 'Home total power': Sending state 128.33800 kWh with 3 decimals of accuracy
[22:43:09][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:12][D][sensor:126]: 'Current Power Consumption': Sending state 0.00000 W with 0 decimals of accuracy
[22:43:12][D][sensor:126]: 'Home daily power': Sending state 1732.92554 kWh with 3 decimals of accuracy
[22:43:12][D][sensor:126]: 'Home total power': Sending state 128.34399 kWh with 3 decimals of accuracy
[22:43:12][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:14][D][sensor:126]: 'Home total power': Sending state 128.34599 kWh with 3 decimals of accuracy
[22:43:14][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:17][D][sensor:126]: 'Current Power Consumption': Sending state 1401.86914 W with 0 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home daily power': Sending state 1732.92761 kWh with 3 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home total power': Sending state 128.34801 kWh with 3 decimals of accuracy
[22:43:17][D][sensor:126]: 'Current Power Consumption': Sending state 240000.00000 W with 0 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home daily power': Sending state 1732.92993 kWh with 3 decimals of accuracy
[22:43:17][D][sensor:126]: 'Home total power': Sending state 128.34900 kWh with 3 decimals of accuracy
[22:43:17][D][binary_sensor:036]: 'Home power monitor': Sending state ON
[22:43:19][D][binary_sensor:036]: 'Home power monitor': Sending state OFF
[22:43:22][D][sensor:126]: 'Current Power Consumption': Sending state 257142.85938 W with 0 decimals of accuracy
[22:43:22][D][sensor:126]: 'Home daily power': Sending state 1733.29260 kWh with 3 decimals of accuracy
[22:43:22][D][sensor:126]: 'Home total power': Sending state 128.35500 kWh with 3 decimals of accuracy
[22:43:22][D][sensor:126]: 'Current Power Consumption': Sending state 3600000.00000 W with 0 decimals of accuracy
```

**Comment by ssieb** [comment] 2022-11-06 23:54
Duplicate of https://github.com/esphome/issues/issues/3730

**Closed by ssieb** 2022-11-06 23:54 UTC

**Comment by emeyedeejay** [comment] 2022-11-07 18:18
> Duplicate of #3730

Thank you and my bad ... I should have searched. My apologies.
