### ISSUE TITLE
Sensor dht generates errors

### ISSUE THREAD

**Issue by HeimoMeyer** [esphome/issues#1297] opened 2020-06-14 13:43 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 nodemcu 32s
**Affected component:**

https://esphome.io/components/sensor/dht.html

**Description of problem:**
After update to Esphome 1.14.4 mr room temps do not work anymore, when building a new ESP32 without sensor component it works and connects to Hassio, when adding the sensor component I get all sorts of errors

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: temp
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "xxxxx"
  password: "xxxx"
  
  manual_ip:
    static_ip: x.x.x.x
    gateway: x.x.x.x
    subnet: x.x.x.x
  
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
sensor:
  - platform: dht
    pin: GPIO4
    model: dht22
    temperature:
      name: "Computer Room Temperature"
    humidity:
      name: "Computer Room Humidity"
    update_interval: 60s

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

INFO Reading configuration /config/esphome/roomtemp.yaml...
INFO Starting log output from x.x.x.x using esphome API
INFO Connecting to x.x.x.x:6053 (x.x.x.x)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to x.x.x.x: [Errno 111] Connection refused). Re-Trying in 1 seconds
INFO Connecting to x.x.x.x:6053 (x.x.x.x)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to x.x.x.x: [Errno 111] Connection refused). Re-Trying in 1 seconds
INFO Connecting to x.x.x.x:6053 (x.x.x.x)
WARNING Initial connection failed. The ESP might not be connected to WiFi yet (Error connecting to x.x.x.x: [Errno 111] Connection refused). Re-Trying in 2 seconds

```

**Additional information and things you've tried:**

The esp32 is connected to wifi but connection refused error (ping confirms it)

After removing the sensor the file uploads and the esp32 is connected again, I have other esp32 with door sensors and they work fine. this happened after esphome upgrade to 1.14.4

**Comment by glmnet** [comment] 2020-06-14 16:09
Duplicate of #1276

**Closed by glmnet** 2020-06-14 16:09 UTC
