### ISSUE TITLE
ESPhome downgrades pyparsing from 3.1.0 to 2.3.1 and then complains because 2.3.1 is incompatible.

### ISSUE THREAD

**Issue by distante** [esphome/issues#4670] opened 2023-07-07 10:20 UTC
### The problem

While trying to build any project that uses `esp-idf` esphome uninstall the valid pyparsing version for an old one and then shows an error because the pyparsing is not compatible:

```
Installing collected packages: pyparsing
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 3.1.0
    Uninstalling pyparsing-3.1.0:
      Successfully uninstalled pyparsing-3.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
esphome 2023.6.4 requires pyparsing>=3.0, but you have pyparsing 2.3.1 which is incompatible.
Successfully installed pyparsing-2.3.1
```

The build continues afterwards

### Which version of ESPHome has the issue?

2023.6.4

### What type of installation are you using?

pip

### What platform are you using?

ESP32-IDF

### Additional information

The same thing happens on docker

**Comment by randybb** [comment] 2023-07-07 15:47
Duplicate of #4517

**Closed by randybb** 2023-07-07 15:47 UTC
