### ISSUE TITLE
Config editor doesn't scroll when accessed via Android app

### ISSUE THREAD

**Issue by cvwillegen** [esphome/issues#3599] opened 2022-09-21 13:37 UTC
### The problem

The latest version, 2022.9.0, includes a new config editor. When I click "Edit" in the interface, the file is opened on screen, but I can't scroll the text. 

This happens when I start the editor via the Esphome dashboard in the Android Companion App.

I tried grabbing the scroll thumb, but that didn't work either. 

### Which version of ESPHome has the issue?

2022.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.9.5

### What platform are you using?

ESP8266

### Additional information

![Screenshot_20220921-153459_Home Assistant](https://user-images.githubusercontent.com/307971/191518407-c1666296-8452-4232-9d50-4befb1a3be68.jpg)

**Comment by ElVit** [comment] 2022-09-21 17:23
Same issue on the iOS companion app.

**Comment by 3ative** [comment] 2022-09-24 00:05
It's an issue with the new editor...
From Microsoft - **"The Monaco editor is not supported in mobile browsers or mobile web frameworks."**

However, I believe there is work being done on this.

**Comment by ssieb** [comment] 2022-09-24 00:17
Duplicate of https://github.com/esphome/dashboard/issues/304

**Closed by ssieb** 2022-09-24 00:17 UTC
