### ISSUE TITLE
auto_uart

### ISSUE THREAD

**Issue by weksupport** [esphome/issues#1858] opened 2021-02-19 09:46 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Debian GNU/Linux 10 (buster)
core-2021.2.3
**ESP (ESP32/ESP8266, Board/Sonoff):**

Current version: 1.16.1
**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
21-02-19 09:26:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/vlc/config.json: Service vlc_telnet not found @ data['discovery'][0]. Got 'vlc_telnet'
21-02-19 09:26:24 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE
21-02-19 09:26:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/core/vlc/config.json: Service vlc_telnet not found @ data['discovery'][0]. Got 'vlc_telnet'
21-02-19 09:26:24 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

```

**Additional information and things you've tried:**

**Comment by randybb** [comment] 2021-02-20 00:04
The VLC thing is not related to esphome.
'auto_uart' again? Next time, please use search - there are are another 2 opened (and a bunch of closed duplicates) issues for the same warning...
Duplicate of #1852
Duplicate of #1837

**Closed by randybb** 2021-02-20 00:04 UTC
