### ISSUE TITLE
Home Assistant warning: [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

### ISSUE THREAD

**Issue by Ghostbuster64** [esphome/issues#1852] opened 2021-02-17 16:16 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Supervised and supported Home Assistant system running Debian10. Home Assistant is running in Docker.

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**
Home Assistant warning: "WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome"

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
21-02-17 15:26:55 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-17 15:26:56 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome (beta)
21-02-17 15:26:56 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-17 15:26:56 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome
21-02-17 15:26:56 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome (beta)
21-02-17 15:26:56 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

```

**Additional information and things you've tried:**
Looked for a new version of ESPHome, but i'm running the latest version already.

**Comment by ludeeus** [comment] 2021-02-17 18:31
Duplicate of https://github.com/esphome/issues/issues/1837

**Closed** 2021-02-20 00:04 UTC
