### ISSUE TITLE
Sen5x Sensor incorrect temperature values

### ISSUE THREAD

**Issue by Smiley098** [esphome/issues#5415] opened 2024-01-21 16:34 UTC
### The problem

At temperatures below 0 degrees, the value 325.6 degrees is displayed.

### Which version of ESPHome has the issue?

2023.12.8

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.5

### What platform are you using?

ESP32

### Board

Esp32dev

### Component causing the issue

Sensoren Sen55

**Comment by ssieb** [comment] 2024-01-21 20:39
Duplicate of https://github.com/esphome/issues/issues/5365
fixed in dev by https://github.com/esphome/esphome/pull/6082

**Closed by ssieb** 2024-01-21 20:39 UTC
