### ISSUE TITLE
Docker image 2021.12.2 broken?

### ISSUE THREAD

**Issue by gfrancesco** [esphome/issues#2864] opened 2021-12-21 21:12 UTC
### The problem

Compiling from yaml doesn't seem to work for me with `2021.12.2` amd64 docker image.
This is the command I'm using:
`docker run --rm -v "${PWD}":/config -it esphome/esphome:2021.12.2 compile my_device.yaml`

All the same, but using 2021.12.1 image works without issues.
See the logs attached for details on the error.

### Which version of ESPHome has the issue?

2021.12.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

NA

### What platform are you using?

ESP8266

### Anything in the logs that might be useful for us?

```txt
Creating cache directory /config/.esphome/platformio
You can change this behavior by mounting a directory to the container's /cache directory.
Traceback (most recent call last):
  File "/usr/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/usr/bin/esphome", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: esphome
```

**Comment by jesserockz** [comment] 2021-12-21 21:26
Duplicate of #2858

**Closed by jesserockz** 2021-12-21 21:26 UTC
