### ISSUE TITLE
Component <xxxxxxxx> took a long time for an operation

### ISSUE THREAD

**Issue by fonske** [esphome/issues#4741] opened 2023-07-24 17:58 UTC
### The problem

I get this error message with the newest version of esphome
Code (brink modbus):
2023.7.0
https://tweakers.net/fotoalbum/image/zH0EflCZgqmE4BkrncqOtkQL.jpg

2023.4.4
https://tweakers.net/fotoalbum/image/Jgu447nRuFHXPu4W6mLGHN0o.jpg

no errors.

Also tried on a different code, same error.

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.3

### What platform are you using?

ESP32

### Board

mhetesp32minikit

**Comment by randybb** [comment] 2023-07-24 18:16
Duplicate of #4717

**Closed by randybb** 2023-07-24 18:16 UTC
