### ISSUE TITLE
What ESP board is this LED controller based on?

### ISSUE THREAD

**Issue by maxtheking** [esphome/issues#87] opened 2019-02-27 18:41 UTC
So a while back i bought a few generic Wi-Fi LED controllers on eBay, i posted images below. They currently use the Tuya cloud, but i want to convert them using tuya-convert so i can control them locally with Home Assistant instead of them reaching out to some chinese Tuya server everytime i turn them on for example. Does anyone know what ESP board they're based on? Can't find any info about them on the internet. 
![img_1112](https://user-images.githubusercontent.com/43993269/53514288-b15bd800-3ac7-11e9-8262-1840c78b338a.JPG)
![img_1113](https://user-images.githubusercontent.com/43993269/53514289-b15bd800-3ac7-11e9-9b15-19ac8aaff188.JPG)

**Comment by brandond** [comment] 2019-02-27 20:46
Open it up and find out. Even if you can't find a specific board for it, you can always use one of the generic board presets that match the available flash size (esp01_1m, etc). At the very least you'll need to figure out what pins the LED outputs map to - either by trial and error, or by tracing with a multimeter.

**Comment by maxtheking** [comment] 2019-02-28 12:27
Opened up the controller, can't find any info on what controller it is though. Had to force the casing open, but this one is bricked so it doesn't matter anyway. I'll try the generic Sonoff-Tasmota on my other ones using Tuya-Convert. 
![img_1121](https://user-images.githubusercontent.com/43993269/53566492-9be4bd80-3b5c-11e9-9be2-854f5508cd22.JPG)
![img_1120](https://user-images.githubusercontent.com/43993269/53566496-9c7d5400-3b5c-11e9-98e3-a6636c68d62a.JPG)

**Comment by OttoWinter** [comment] 2019-03-01 15:29
Without the name or anything else there's no way we can help here (not even sure if it's an ESP, the PCB looks a bit weird).

I will close this issue since this bug tracker is for bugs, not general questions

**Closed by OttoWinter** 2019-03-01 15:29 UTC

**Comment by CinoNY** [comment] 2019-03-28 03:47
@maxtheking I can confirm you can flash this with tuya-convert. Haven't gotten far with it yet, but i'm in process of adding the device to HA via mqtt.
