### ISSUE TITLE
Esphome 2023.4 Break MAX7219 Digit Display

### ISSUE THREAD

**Issue by JbbDE** [esphome/issues#4437] opened 2023-04-20 21:15 UTC
### The problem

Since I have updated all my devices to esphome 2023.4,
the 4 chip MAX7219 digit display isn't showing information properly.
The text displayed is messed up on all segments, making information unreadable.

This is how time is displayed (should show smth like 22:35, other pages are also messed up):

![IMG20230420223612](https://user-images.githubusercontent.com/70019640/233488989-7fd81871-2f5b-469c-8d30-80d556850a47.jpg)

### Which version of ESPHome has the issue?

2023.4.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4

### What platform are you using?

ESP8266

### Board

d1_mini_lite

### Component causing the issue

MAX7219

### Example YAML snippet

```yaml
esphome:
  name: matrix-display

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***"

ota:
  password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Matrix-Display Fallback Hotspot"
    password: "***"

captive_portal:
    
spi:
  clk_pin: D6
  mosi_pin: D8


time:
  - platform: homeassistant
    id: hass_time

sensor:
  - platform: homeassistant
    id: aussentemperatur
    entity_id: sensor.outdoor_temperature
    internal: True
  
  - platform: homeassistant
    id: regenrate
    entity_id: sensor.event_rain_rate
    internal: true
  
  - platform: homeassistant
    id: windstoss
    entity_id: sensor.wind_gust
    internal: True

  - platform: homeassistant
    id: strahlung
    entity_id: sensor.durchschnittliche_strahlung_pro_stunde
    internal: True
  
  - platform: homeassistant
    id: helligkeit
    entity_id: input_number.helligkeit_max7219_matrix
    internal: True
  


text_sensor:  
  - platform: homeassistant
    id: texthassio
    entity_id: input_text.max7219_matrix_freitext
    internal: True
  

  

globals:
  - id: display_page
    type: int
    restore_value: no
    initial_value: '1'


display:
  - platform: max7219digit
    cs_pin: D7
    num_chips: 4
    update_interval: 30s
    scroll_speed: 40ms
    id: mein_display
    lambda: |-
                it.intensity(id(helligkeit).state);
                if (id(display_page) == 1) {
                  it.strftime(0, 0, id(digit_font), "%H:%M", id(hass_time).now());
                  } else {
                    if (id(display_page) == 2) {
                    it.printf(0, 0, id(digit_font), "Aussentemperatur: %7.2f°C ", id(aussentemperatur).state); 
                    } else {
                      if (id(display_page) == 3) {
                      it.printf(0, 0, id(digit_font), "Aktuelle Eventregenrate: %7.1fmm/h ", id(regenrate).state); 
                      } else {
                        if (id(display_page) == 4) { 
                        it.printf(0, 0, id(digit_font), "Windstoesse: %7.2fkm/h", id(windstoss).state); 
                          } else {
                            if (id(display_page) == 5) {
                              it.printf(0, 0, id(digit_font), "%s", id(texthassio).state.c_str());
                              id(display_page) = 0;
                          }
                        
                        } } } };
                id(display_page) ++;

font:
  - file: "pixelmix.ttf"
    id: digit_font
    size: 8
```

### Anything in the logs that might be useful for us?

```txt
Logs show no errors.
```

**Comment by voed** [comment] 2023-04-20 21:51
Welcome to the club #4432

**Comment by Marlo461** [comment] 2023-04-21 05:16
I have the same problem! In the evening, I spent about an hour on it, but I didn't figure out where the problem was.

**Comment by michalpulda** [comment] 2023-04-21 13:40
Same problem here.

**Comment by ssieb** [comment] 2023-04-22 07:26
Duplicate of https://github.com/esphome/issues/issues/4432

**Comment by naamah75** [comment] 2023-04-22 08:48
Same problem, after update

**Comment by Zubor79** [comment] 2023-04-22 12:31
Update 2023.4 flipped all symbols.

**Comment by DeepCoreSystem** [comment] 2023-04-22 14:10
I have exactly the same problem, with an almost identical setup, i.e. no _flip_x_, no _reverse_enable_ and no _rotate_chip_ set in my yaml ... 
The [dirty fix](https://github.com/esphome/issues/issues/4432#issuecomment-1516484884)  by @voed does help !!

**Comment by fire1ce** [comment] 2023-04-22 17:01
+1

**Comment by ssieb** [comment] 2023-04-22 19:10
There's a fix in dev, will be in the next point release.

**Closed by ssieb** 2023-04-22 19:10 UTC
