### ISSUE TITLE
Resolving IP fails on API connection

### ISSUE THREAD

**Issue by tedenda** [esphome/issues#2581] opened 2021-10-21 10:59 UTC
### The problem

For some reason IP is resolved correctly when updating firmware but not when trying to connect to API for looking at the log output.

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP8266

### Board

d1_mini

### Anything in the logs that might be useful for us?

```txt
INFO Successfully compiled program.
INFO Resolving IP address of eh-vp-fighter1215.local
INFO  -> 192.168.1.238
INFO Uploading /data/eh-vp-fighter1215/.pioenvs/eh-vp-fighter1215/firmware.bin (432048 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from eh-vp-fighter1215.local using esphome API
WARNING Can't connect to ESPHome API for eh-vp-fighter1215.local: Error resolving IP address: [Errno -2] Name or service not known
INFO Trying to reconnect to eh-vp-fighter1215.local in the background
```

**Comment by OttoWinter** [comment] 2021-10-21 11:55
Duplicate of https://github.com/esphome/issues/issues/2551

**Closed by OttoWinter** 2021-10-21 11:55 UTC
