### ISSUE TITLE
Increase BLE range

### ISSUE THREAD

**Issue by blademckain** [esphome/issues#501] opened 2019-07-03 10:54 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**
esp32

**Affected component:**
platform: ESP32

**Description of problem:**
is it possible to increase the BLE range, as indicated at this link?
https://github.com/nkolban/esp32-snippets/issues/674

using this code
`esp_err_t errRc=esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT,ESP_PWR_LVL_P9);
esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_P9);
 esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_SCAN ,ESP_PWR_LVL_P9); `

**Comment by OttoWinter** [comment] 2019-07-03 13:05
1. This is a feature request, not an issue
2. Duplicate of https://github.com/esphome/esphome/issues/311

**Closed by OttoWinter** 2019-07-03 13:05 UTC
