### ISSUE TITLE
Cannot adopt device

### ISSUE THREAD

**Issue by rickythewoof** [esphome/issues#5652] opened 2024-03-28 14:45 UTC
### The problem

When I try to adopt the device which I've flashed with the web tool flasher it says that it can't do it. Problem relies in the fact that the link for the raw file is not existent. Needs to get changed.

Tried every version of esphome available but everyone gives me the same issues

2024-03-28 15:43:27,184 ERROR Error while fetching https://raw.githubusercontent.com/esphome/firmware/v2/esphome-web/esp32c3.yaml: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/esphome/firmware/v2/esphome-web/esp32c3.yaml

### Which version of ESPHome has the issue?

2024-4-0-dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP32

### Board

Esp32-c3

**Comment by ssieb** [comment] 2024-03-28 20:44
Duplicate of https://github.com/esphome/issues/issues/5645

**Closed by ssieb** 2024-03-28 20:44 UTC
