### ISSUE TITLE
Exception: AttributeError: 'NoneType' object has no attribute 'cancel'

### ISSUE THREAD

**Issue by akasma74** [esphome/issues#108] opened 2019-03-07 21:08 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io 0.89.0

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266, Wemos D1 mini

**Affected component:**
?

**Description of problem:**
All of sudden get the exception in the log
````
Exception in thread Thread-207274:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/akasma74/devel/pio/lib/python2.7/site-packages/esphome/api/client.py", line 138, in func
    self._refresh_ping()
  File "/Users/akasma74/devel/pio/lib/python2.7/site-packages/esphome/api/client.py", line 126, in _refresh_ping
    self._ping_timer.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
````
The node is apparently keep working though..

**Problem-relevant YAML-configuration entries:**
```


```

**Traceback (if applicable):**
```

```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment] 2019-03-08 11:33
Duplicate of https://github.com/esphome/issues/issues/74

**Closed by OttoWinter** 2019-03-08 11:33 UTC
