### ISSUE TITLE
ezo_pmp component failing on compile

### ISSUE THREAD

**Issue by stevewull** [esphome/issues#4297] opened 2023-03-09 23:08 UTC
### The problem

Using the Atlas Scientific Hydroponics Kit. Have three EZO pumps connected over I2C bus. My Yaml passes the validation test.  But when I try to compile and install, it gives the error message below.

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.3.3

### What platform are you using?

ESP32

### Board

adafruit huzzah32

### Component causing the issue

ezo_pmp

### Example YAML snippet

```yaml
i2c:
  sda: 23
  scl: 22
  scan: True
  id: bus_a


ezo_pmp:
  - id: ezo_pmp_tasA
    address: 108
    update_interval: 60s


  - id: ezo_pmp_tabB
    address: 109
    update_interval: 60s

  - id: ezo_pmp_pHdown
    address: 110
    update_interval: 60s

sensor:

  - platform: ezo
    id: rtd_ezo
    name: "Temperature"
    i2c_id: bus_a
    address: 102
    accuracy_decimals: 2
    unit_of_measurement: "°C"
    update_interval: 10s 

  - platform: ezo
    id: ph_ezo
    name: "pH"
    address: 99
    accuracy_decimals: 2
    unit_of_measurement: "pH"
    update_interval: 10s

  - platform: ezo
    id: ec_ezo
    name: "Conductivity"
    address: 100
    accuracy_decimals: 2
    unit_of_measurement: "μS/cm"
    update_interval: 10s
```

### Anything in the logs that might be useful for us?

```txt
src/esphome/components/ezo_pmp/ezo_pmp.cpp: In member function 'virtual void esphome::ezo_pmp::EzoPMP::update()':
src/esphome/components/ezo_pmp/ezo_pmp.cpp:55:86: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'calibration_status_'; did you mean 'set_calibration_volume'?
     this->queue_command_(EZO_PMP_COMMAND_READ_CALIBRATION_STATUS, 0, 0, (bool) this->calibration_status_);
                                                                                      ^~~~~~~~~~~~~~~~~~~
                                                                                      set_calibration_volume
src/esphome/components/ezo_pmp/ezo_pmp.cpp: In member function 'void esphome::ezo_pmp::EzoPMP::read_command_result_()':
src/esphome/components/ezo_pmp/ezo_pmp.cpp:193:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'is_dosing_'; did you mean 'is_waiting_'?
       if (this->is_dosing_)
                 ^~~~~~~~~~
                 is_waiting_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:194:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'is_dosing_'; did you mean 'is_waiting_'?
         this->is_dosing_->publish_state(this->is_dosing_flag_);
               ^~~~~~~~~~
               is_waiting_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:202:19: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
         if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_NONE)
                   ^~~~~~~~~~~~
                   is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:202:41: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
         if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_NONE)
                                         ^~~~~~~~~~~~
                                         is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:203:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
           this->dosing_mode_->publish_state(DOSING_MODE_NONE);
                 ^~~~~~~~~~~~
                 is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:223:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'is_paused_'; did you mean 'is_failed'?
       if (this->is_paused_)
                 ^~~~~~~~~~
                 is_failed
src/esphome/components/ezo_pmp/ezo_pmp.cpp:224:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'is_paused_'; did you mean 'is_failed'?
         this->is_paused_->publish_state(this->is_paused_flag_);
               ^~~~~~~~~~
               is_failed
src/esphome/components/ezo_pmp/ezo_pmp.cpp:238:56: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'calibration_status_'; did you mean 'set_calibration_volume'?
       if (parsed_second_parameter.has_value() && this->calibration_status_) {
                                                        ^~~~~~~~~~~~~~~~~~~
                                                        set_calibration_volume
src/esphome/components/ezo_pmp/ezo_pmp.cpp:240:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'calibration_status_'; did you mean 'set_calibration_volume'?
           this->calibration_status_->publish_state("Fixed Volume");
                 ^~~~~~~~~~~~~~~~~~~
                 set_calibration_volume
src/esphome/components/ezo_pmp/ezo_pmp.cpp:242:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'calibration_status_'; did you mean 'set_calibration_volume'?
           this->calibration_status_->publish_state("Volume/Time");
                 ^~~~~~~~~~~~~~~~~~~
                 set_calibration_volume
src/esphome/components/ezo_pmp/ezo_pmp.cpp:244:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'calibration_status_'; did you mean 'set_calibration_volume'?
           this->calibration_status_->publish_state("Fixed Volume & Volume/Time");
                 ^~~~~~~~~~~~~~~~~~~
                 set_calibration_volume
src/esphome/components/ezo_pmp/ezo_pmp.cpp:246:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'calibration_status_'; did you mean 'set_calibration_volume'?
           this->calibration_status_->publish_state("Uncalibrated");
                 ^~~~~~~~~~~~~~~~~~~
                 set_calibration_volume
src/esphome/components/ezo_pmp/ezo_pmp.cpp:259:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_VOLUME)
                 ^~~~~~~~~~~~
                 is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:259:39: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_VOLUME)
                                       ^~~~~~~~~~~~
                                       is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:260:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
         this->dosing_mode_->publish_state(DOSING_MODE_VOLUME);
               ^~~~~~~~~~~~
               is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:264:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_VOLUME_OVER_TIME)
                 ^~~~~~~~~~~~
                 is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:264:39: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_VOLUME_OVER_TIME)
                                       ^~~~~~~~~~~~
                                       is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:265:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
         this->dosing_mode_->publish_state(DOSING_MODE_VOLUME_OVER_TIME);
               ^~~~~~~~~~~~
               is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:269:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_CONSTANT_FLOW_RATE)
                 ^~~~~~~~~~~~
                 is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:269:39: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_CONSTANT_FLOW_RATE)
                                       ^~~~~~~~~~~~
                                       is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:270:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
         this->dosing_mode_->publish_state(DOSING_MODE_CONSTANT_FLOW_RATE);
               ^~~~~~~~~~~~
               is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:274:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_CONTINUOUS)
                 ^~~~~~~~~~~~
                 is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:274:39: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_CONTINUOUS)
                                       ^~~~~~~~~~~~
                                       is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:275:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
         this->dosing_mode_->publish_state(DOSING_MODE_CONTINUOUS);
               ^~~~~~~~~~~~
               is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:280:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'is_paused_'; did you mean 'is_failed'?
       if (this->is_paused_)
                 ^~~~~~~~~~
                 is_failed
src/esphome/components/ezo_pmp/ezo_pmp.cpp:281:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'is_paused_'; did you mean 'is_failed'?
         this->is_paused_->publish_state(this->is_paused_flag_);
               ^~~~~~~~~~
               is_failed
src/esphome/components/ezo_pmp/ezo_pmp.cpp:282:17: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_NONE)
                 ^~~~~~~~~~~~
                 is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:282:39: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
       if (this->dosing_mode_ && this->dosing_mode_->state != DOSING_MODE_NONE)
                                       ^~~~~~~~~~~~
                                       is_dosing_flag_
src/esphome/components/ezo_pmp/ezo_pmp.cpp:283:15: error: 'class esphome::ezo_pmp::EzoPMP' has no member named 'dosing_mode_'; did you mean 'is_dosing_flag_'?
         this->dosing_mode_->publish_state(DOSING_MODE_NONE);
               ^~~~~~~~~~~~
               is_dosing_flag_
*** [/data/hydro1-tomato-station/.pioenvs/hydro1-tomato-station/src/esphome/components/ezo_pmp/ezo_pmp.cpp.o] Error 1
========================== [FAILED] Took 4.37 seconds ==========================
```

**Comment by stevewull** [comment] 2023-03-11 20:40
I notice that this was reported in issue #3832.  As per temporary fix discussed there, I added the following:

binary_sensor:
  - platform: ezo_pmp
    pump_state:
      id: pump_state
      name: Pump State      
  - platform: ezo_pmp
    is_paused:
      id: is_paused
      name: Is Paused  

The code now compiles.

**Comment by V4l3n10** [comment] 2023-03-25 07:59
Guys, 
Have any of you managed to set up a multi-ezo_pmp configuration? A configuration example would be much appreciated.

**Comment by ssieb** [comment] 2023-03-25 08:08
@V4l3n10, that is not related to this issue and github issues are not for support requests.  Ask on the discord server or one of the forums.

**Comment by ssieb** [comment] 2023-03-25 08:13
@V4l3n10, also there is literally an example right at the top of this issue...

**Comment by ssieb** [comment] 2023-03-25 08:13
This is a duplicate of https://github.com/esphome/issues/issues/3832.

**Closed by ssieb** 2023-03-25 08:13 UTC
