### ISSUE TITLE
Dallas causes "Starting scan..." reboot

### ISSUE THREAD

**Issue by LaG1924** [esphome/issues#498] opened 2019-07-02 16:17 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Compiling and uploading code to ESP8266 from OrangePiZero board that also hosts Home Assistant.
Using version 1.13.6 installed by pip.

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU v2.

**Affected component:**

Dallas temperature sensor (ds18b20)

**Description of problem:**
When `dallas` enabled, device repeatedly reboots with last message `Starting scan...`

**Problem-relevant YAML-configuration entries:**
Working
```yaml
esphome:
  name: workroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "Welcome99124768"
  password: "99124768"

logger:

api:

ota:

# dallas:
#  - pin: D1

#sensor:
#  - platform: dallas
#    index: 0
#    name: "Temperature"

switch:
  - platform: gpio
    pin:
      number: 16
      inverted: yes
    name: "Onboard LED"
```

Not working
```yaml
esphome:
  name: workroom
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "Welcome99124768"
  password: "99124768"

logger:

api:

ota:

dallas:
 - pin: D1

#sensor:
#  - platform: dallas
#    index: 0
#    name: "Temperature"

switch:
  - platform: gpio
    pin:
      number: 16
      inverted: yes
    name: "Onboard LED"
```

**Logs (if applicable):**

Not working
```
INFO Successfully uploaded program.
INFO Starting log output from /dev/ttyUSB0 with baud rate 115200
[16:07:15]011]: Setting up GPIO Switch 'Onboard LED'...
[16:07:15][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:15][D][switch:045]: 'Onboard LED': Sending state OFF
[16:07:15][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:15][C][dallas.sensor:032]: Setting up DallasComponent...
[16:07:15][C][wifi:029]: Setting up WiFi...
[16:07:15][D][wifi:272]: Starting scan...
[16:07:24]
[16:07:24] ets Jan  8 2013,rst cause:4, boot mode:(3,6)
[16:07:24]
[16:07:24]wdt reset
[16:07:24]load 0x4010f000, len 1384, room 16
[16:07:24]tail 8
[16:07:24]chksum 0x2d
[16:07:24]csum 0x2d
[16:07:24]vbb28d4a3
[16:07:24]~ld
[16:07:24][I][logger:116]: Log initialized
[16:07:24][C][ota:364]: There have been 1 suspected unsuccessful boot attempts.
[16:07:24][I][app:028]: Running through setup()...
[16:07:24][C][switch.gpio:011]: Setting up GPIO Switch 'Onboard LED'...
[16:07:24][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:24][D][switch:045]: 'Onboard LED': Sending state OFF
[16:07:24][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:24][C][dallas.sensor:032]: Setting up DallasComponent...
[16:07:24][C][wifi:029]: Setting up WiFi...
[16:07:24][D][wifi:272]: Starting scan...
[16:07:32]
[16:07:32] ets Jan  8 2013,rst cause:4, boot mode:(3,6)
[16:07:32]
[16:07:32]wdt reset
[16:07:32]load 0x4010f000, len 1384, room 16
[16:07:32]tail 8
[16:07:32]chksum 0x2d
[16:07:32]csum 0x2d
[16:07:32]vbb28d4a3
[16:07:32]~ld
[16:07:32][I][logger:116]: Log initialized
[16:07:32][C][ota:364]: There have been 2 suspected unsuccessful boot attempts.
[16:07:32][I][app:028]: Running through setup()...
[16:07:32][C][switch.gpio:011]: Setting up GPIO Switch 'Onboard LED'...
[16:07:32][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:32][D][switch:045]: 'Onboard LED': Sending state OFF
[16:07:32][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:32][C][dallas.sensor:032]: Setting up DallasComponent...
[16:07:32][C][wifi:029]: Setting up WiFi...
[16:07:32][D][wifi:272]: Starting scan...
[16:07:41]
[16:07:41] ets Jan  8 2013,rst cause:4, boot mode:(3,6)
[16:07:41]
[16:07:41]wdt reset
[16:07:41]load 0x4010f000, len 1384, room 16
[16:07:41]tail 8
[16:07:41]chksum 0x2d
[16:07:41]csum 0x2d
[16:07:41]vbb28d4a3
[16:07:41]~ld
[16:07:41][I][logger:116]: Log initialized
[16:07:41][C][ota:364]: There have been 3 suspected unsuccessful boot attempts.
[16:07:41][I][app:028]: Running through setup()...
[16:07:41][C][switch.gpio:011]: Setting up GPIO Switch 'Onboard LED'...
[16:07:41][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:41][D][switch:045]: 'Onboard LED': Sending state OFF
[16:07:41][D][switch:025]: 'Onboard LED' Turning OFF.
[16:07:41][C][dallas.sensor:032]: Setting up DallasComponent...
[16:07:41][C][wifi:029]: Setting up WiFi...
[16:07:41][D][wifi:272]: Starting scan...
```

Working
```
INFO Successfully uploaded program.
INFO Starting log output from /dev/ttyUSB0 with baud rate 115200
[15:54:36]][switch.gpio:011]: Setting up GPIO Switch 'Onboard LED'...
[15:54:36][D][switch:025]: 'Onboard LED' Turning OFF.
[15:54:36][D][switch:045]: 'Onboard LED': Sending state OFF
[15:54:36][D][switch:025]: 'Onboard LED' Turning OFF.
[15:54:36][C][wifi:029]: Setting up WiFi...
[15:54:36][D][wifi:272]: Starting scan...
[15:54:42][D][wifi:287]: Found networks:
[15:54:42][I][wifi:322]: - 'Welcome99124768' (7C:39:53:91:66:C9) ▂▄▆█
[15:54:42][D][wifi:323]:     Channel: 7
[15:54:42][D][wifi:324]:     RSSI: -18 dB
[15:54:42][D][wifi:326]: - 'FallbackNet' (7E:39:53:91:66:C9) ▂▄▆█
[15:54:42][D][wifi:326]: - 'CERN-3396-N1134' (7C:8B:CA:5B:26:3A) ▂▄▆█
[15:54:42][I][wifi:164]: WiFi Connecting to 'Welcome99124768'...
[15:54:44][I][wifi:380]: WiFi connected!
[15:54:44][C][wifi:254]:   SSID: 'Welcome99124768'
[15:54:44][C][wifi:255]:   IP Address: 192.168.1.89
[15:54:44][C][wifi:257]:   BSSID: 7C:39:53:91:66:C9
[15:54:44][C][wifi:258]:   Hostname: 'workroom'
[15:54:44][C][wifi:262]:   Signal strength: -29 dB ▂▄▆█
[15:54:44][C][wifi:263]:   Channel: 7
[15:54:44][C][wifi:264]:   Subnet: 255.255.255.0
[15:54:44][C][wifi:265]:   Gateway: 192.168.1.1
[15:54:44][C][wifi:266]:   DNS1: 8.8.8.8
[15:54:44][C][wifi:267]:   DNS2: 8.8.4.4
[15:54:45][C][ota:029]: Over-The-Air Updates:
[15:54:45][C][ota:030]:   Address: workroom.local:8266
[15:54:45][C][api:030]: Setting up Home Assistant API server...
[15:54:45][I][app:060]: setup() finished successfully!
[15:54:45][I][app:096]: esphome version 1.13.6 compiled on Jul  2 2019, 15:53:22
[15:54:45][C][wifi:372]: WiFi:
[15:54:45][C][wifi:254]:   SSID: 'Welcome99124768'
[15:54:45][C][wifi:255]:   IP Address: 192.168.1.89
[15:54:45][C][wifi:257]:   BSSID: 7C:39:53:91:66:C9
[15:54:45][C][wifi:258]:   Hostname: 'workroom'
[15:54:45][C][wifi:262]:   Signal strength: -29 dB ▂▄▆█
[15:54:45][C][wifi:263]:   Channel: 7
[15:54:45][C][wifi:264]:   Subnet: 255.255.255.0
[15:54:45][C][wifi:265]:   Gateway: 192.168.1.1
[15:54:45][C][wifi:266]:   DNS1: 8.8.8.8
[15:54:45][C][wifi:267]:   DNS2: 8.8.4.4
[15:54:45][C][switch.gpio:042]: GPIO Switch 'Onboard LED'
[15:54:45][C][switch.gpio:043]:   Pin: GPIO16 (Mode: OUTPUT, INVERTED)
[15:54:45][C][switch.gpio:059]:   Restore Mode: Restore (Defaults to OFF)
[15:54:45][C][logger:137]: Logger:
[15:54:45][C][logger:138]:   Level: DEBUG
[15:54:45][C][logger:139]:   Log Baud Rate: 115200
[15:54:45][C][logger:140]:   Hardware UART: UART0
[15:54:45][C][ota:029]: Over-The-Air Updates:
[15:54:45][C][ota:030]:   Address: workroom.local:8266
[15:54:45][C][api:103]: API Server:
[15:54:45][C][api:104]:   Address: workroom.local:6053
[15:54:57][D][api:573]: Client 'Home Assistant 0.95.4 (192.168.1.70)' connected successfully!
```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment] 2019-07-03 13:06
Duplicate of https://github.com/esphome/issues/issues/455 - if it were the dallas code itself, the error would appear right after `Setting up DallasComponent...`

**Closed by OttoWinter** 2019-07-03 13:06 UTC
