### ISSUE TITLE
Samsung remote receiver

### ISSUE THREAD

**Issue by DelukaDZ** [esphome/issues#381] opened 2019-06-01 15:56 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Host system HassOS 2.11
Hass.io supervisor version 165
ESPHome 1.13.2
Home Assistant 0.93.2

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP 8266 Wemos Lolin nodemcu v3

**Affected component:**

Remote Receiver

**Description of problem:**

the problem is that the sensor triggers on every button i press on the Samsung remote and not only on the poweroff button.
its not triggered with any other remote i have

**Problem-relevant YAML-configuration entries:**
```yaml
remote_receiver:
  pin: 
    number: GPIO14
    inverted: yes
    mode: INPUT_PULLUP
  dump: samsung

binary_sensor:
  - platform: remote_receiver
    name: "Samsung Remote"
    samsung:
      data : 0xE0E040BF
    filters:
      - delayed_off: 200ms

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**
Asked for help on the Hassio forum
Used a other members and i have the same problem

**Comment by OttoWinter** [comment] 2019-06-01 15:57
Duplicate of https://github.com/esphome/issues/issues/369

**Closed by OttoWinter** 2019-06-01 15:57 UTC
Labels: component: remote_receiver

**Comment by DelukaDZ** [comment] 2019-06-01 16:11
Well its still not working and no answer on how to fix it

**Comment by OttoWinter** [comment] 2019-06-01 16:12
-> 1.13.3

**Comment by DelukaDZ** [comment] 2019-06-01 22:04
thx
