### ISSUE TITLE
Two different versions of library included when loading web_server component

### ISSUE THREAD

**Issue by prabbit237** [esphome/issues#751] opened 2019-10-20 05:18 UTC
**Ubuntu Python3 pip3 Two different machines/setups One running in docker/has.io and the other just from CLI**

**ESP (ESP8266):**

**Nodemcuv2:**

https://esphome.io/components/web_server.html

**Adding web_server component causes it to load/compile two different versions of ESPAsyncTCP. Just started today.

Dependency Graph
|-- \<ArduinoJson-esphomelib\> 5.13.3
|-- \<ESP Async WebServer> 1.1.1
|   |-- \<ESPAsyncTCP> 1.2.2   =================
|   |   |-- \<ESP8266WiFi> 1.0
|   |-- \<Hash> 1.0
|   |-- \<ESP8266WiFi> 1.0
|   |-- \<ArduinoJson-esphomelib> 5.13.3
|-- \<ESP8266WiFi> 1.0
|-- \<ESP8266mDNS>
|   |-- \<ESP8266WiFi> 1.0
|-- \<ESPAsyncTCP> 1.2.0   ===================
|   |-- \<ESP8266WiFi> 1.0
|-- \<ESPAsyncTCP> 1.2.2   ===================
|   |-- \<ESP8266WiFi> 1.0

Removing the web_server component compiles fine.

**

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test_node
  platform: ESP8266
  board: nodemcuv2

logger:
  level: DEBUG
  
  
wifi:
      ssid: "MYSSID"
      password: "MYPASSWORD"

# Enable Home Assistant API
api:

ota:

#if I delete the below lines, it's fine.
web_server:
 port: 80
  

```

```
**INFO Reading configuration...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /opt/esphome/test_node
Processing test_node (board: nodemcuv2; framework: arduino; platform: espressif8266@1.8.0)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 1.8.0 > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: toolchain-xtensa 1.40802.0 (4.8.2), framework-arduinoespressif8266 2.20402.4 (2.4.2), tool-esptool 1.413.0 (4.13)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Looking for Update library in registry
Warning! Library `{'name': 'Update', 'requirements': None}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'name': 'Update', 'requirements': None}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.
Found 30 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP Async WebServer> 1.1.1
|   |-- <ESPAsyncTCP> 1.2.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.2.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncTCP> 1.2.2
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/test_node/src/main.cpp.o
Linking .pioenvs/test_node/firmware.elf
.pioenvs/test_node/lib974/libESPAsyncTCP_ID305@1.2.0.a(ESPAsyncTCP.cpp.o): In function `AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, long)':
ESPAsyncTCP.cpp:(.text._ZN11AsyncClient7_s_recvEPvP7tcp_pcbP4pbufl+0x4): multiple definition of `AsyncClient::_s_recv(void*, tcp_pcb*, pbuf*, long)'
.pioenvs/test_node/liba41/libESPAsyncTCP_ID305.a(ESPAsyncTCP.cpp.o):ESPAsyncTCP.cpp:(.text._ZN11AsyncClient7_s_recvEPvP7tcp_pcbP4pbufl+0x10): first defined here
.pioenvs/test_node/lib974/libESPAsyncTCP_ID305@1.2.0.a(ESPAsyncTCP.cpp.o): In function `AsyncClient::_s_sent(void*, tcp_pcb*, unsigned short)':
ESPAsyncTCP.cpp:(.text._ZN11AsyncClient7_s_sentEPvP7tcp_pcbt+0x4): multiple definition of `AsyncClient::_s_sent(void*, tcp_pcb*, unsigned short)'
.pioenvs/test_node/liba41/libESPAsyncTCP_ID305.a(ESPAsyncTCP.cpp.o):ESPAsyncTCP.cpp:(.text._ZN11AsyncClient7_s_sentEPvP7tcp_pcbt+0x10): first defined here
.pioenvs/test_node/lib974/libESPAsyncTCP_ID305@1.2.0.a(ESPAsyncTCP.cpp.o): In function `AsyncClient::_s_error(void*, long)':**

```

**Additional information and things you've tried:**

Modifying the platformio.ini file and commenting out the one library will then allow "pio run" to compile successfully

; Auto generated code by esphome

[common]
lib_deps =
build_flags =
upload_flags =

; ===== DO NOT EDIT ANYTHING BELOW THIS LINE =====
; ========== AUTO GENERATED CODE BEGIN ===========
[env:test_node]
board = nodemcuv2
board_build.flash_mode = dout
build_flags =
    -DESPHOME_LOG_LEVEL=ESPHOME_LOG_LEVEL_DEBUG
    -DUSE_STORE_LOG_STR_IN_FLASH
    -Wl,-Teagle.flash.4m.ld
    -Wno-sign-compare
    -Wno-unused-but-set-variable
    -Wno-unused-variable
    -fno-exceptions
    ${common.build_flags}
framework = arduino
lib_deps =
    ArduinoJson-esphomelib@5.13.3
    ESP Async WebServer@1.1.1
    ESP8266WiFi
    ESP8266mDNS
;    ESPAsyncTCP@1.2.0                                          commented out this line
    Update
    ${common.lib_deps}
platform = espressif8266@1.8.0
upload_speed = 115200
; =========== AUTO GENERATED CODE END ============
; ========= YOU CAN EDIT AFTER THIS LINE =========

**Comment by OttoWinter** [comment] 2019-10-20 13:34
Duplicate of https://github.com/esphome/issues/issues/683

**Closed by OttoWinter** 2019-10-20 13:34 UTC
