### ISSUE TITLE
http_request seems to cache the first command it POSTS

### ISSUE THREAD

**Issue by krugerrc** [esphome/issues#1343] opened 2020-07-11 13:02 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 and ESP8266
**ESPHome version (latest production, beta, dev branch)**

1.15-dev
**Affected component:**

**Description of problem:**
http_request seems to cache the first command it POSTS. I have two esp's - an ESP32 configured as a light switch for two lights, using the touch sensor, and an esp8266 (Wemos D1 Mini) as a relay controller. On the first switch event triggered on the ESP32, the correct light is switched on. But after this, it doesn't matter which switch event is triggered, the first light is switched on or off.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: relays
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "xxxx"
  password: "xxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Relays Fallback Hotspot"
    password: "v88cmfQUnfDL"

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

switch:
  - platform: gpio
    pin: 
      number: D0
      inverted: no
    name: "living_room_light"
    id: "lr_light"
  - platform: gpio
    pin: 
      number: D5
      inverted: no
    name: "dining_room_light"
    id: "dr_light"

```
```yaml
esphome:
  name: direct_l_switch
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: "xxxx"
  password: "xxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Direct L Switch Fallback Hotspot"
    password: "sKrNs7fBFtaa"

captive_portal:

# Enable logging
logger:
  level: VERBOSE
# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

http_request:

esp32_touch:
    setup_mode: false
    
binary_sensor:

  - platform: esp32_touch
    threshold: 1200
    name: switch_1
    id: switch_1
    pin: GPIO12
    on_press:
      then:
        - http_request.post:
            url: http://192.168.8.125/switch/living_room_light/toggle

  - platform: esp32_touch
    threshold: 1200
    name: switch_2
    pin: GPIO33
    id: switch_2
    on_press:
      then:
        - http_request.post:
            url: http://192.168.8.125/switch/dining_room_light/toggle
```

**Logs (if applicable):**

```
Logfile for ESP32
[14:14:59][D][binary_sensor:036]: 'switch_1': Sending state ON
[14:14:59][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/living_room_light/toggle; Code: 200
[14:15:00][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/living_room_light; Code: 200
[14:15:00][V][app:077]: A component took a long time in a loop() cycle (0.42 s).
[14:15:00][V][app:078]: Components should block for at most 20-30ms in loop().
[14:15:00][D][binary_sensor:036]: 'switch_1': Sending state OFF
[14:15:03][D][binary_sensor:036]: 'switch_2': Sending state ON
[14:15:04][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/dining_room_light/toggle; Code: 200
[14:15:04][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/dining_room_light; Code: 200
[14:15:04][V][app:077]: A component took a long time in a loop() cycle (0.28 s).
[14:15:04][V][app:078]: Components should block for at most 20-30ms in loop().
[14:15:04][D][binary_sensor:036]: 'switch_2': Sending state OFF
[14:15:07][D][binary_sensor:036]: 'switch_1': Sending state ON
[14:15:07][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/living_room_light/toggle; Code: 200
[14:15:07][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/living_room_light; Code: 200
[14:15:07][V][app:077]: A component took a long time in a loop() cycle (0.29 s).
[14:15:07][V][app:078]: Components should block for at most 20-30ms in loop().
[14:15:07][D][binary_sensor:036]: 'switch_1': Sending state OFF
[14:15:09][D][binary_sensor:036]: 'switch_2': Sending state ON
[14:15:09][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/dining_room_light/toggle; Code: 200
[14:15:10][D][http_request:060]: HTTP Request completed; URL: http://192.168.8.125/switch/dining_room_light; Code: 200
[14:15:10][V][app:077]: A component took a long time in a loop() cycle (0.29 s).
[14:15:10][V][app:078]: Components should block for at most 20-30ms in loop().
[14:15:10][D][binary_sensor:036]: 'switch_2': Sending state OFF

```
```
Logfile for Wemos D1 Mini
[14:14:46][D][api.connection:604]: Client 'Home Assistant 0.111.3 (192.168.8.124)' connected successfully!
[14:14:59][D][switch:029]: 'living_room_light' Toggling ON.
[14:14:59][D][switch:045]: 'living_room_light': Sending state ON
[14:15:04][D][switch:029]: 'living_room_light' Toggling OFF.
[14:15:04][D][switch:045]: 'living_room_light': Sending state OFF
[14:15:07][D][switch:029]: 'living_room_light' Toggling ON.
[14:15:07][D][switch:045]: 'living_room_light': Sending state ON
[14:15:09][D][switch:029]: 'living_room_light' Toggling OFF.
[14:15:09][D][switch:045]: 'living_room_light': Sending state OFF
```
**Additional information and things you've tried:**
I have rechecked my yaml files endlessly, and do not see an issue. However, I'm not sure whether this is a bug, or I'm missing something.

**Comment by glmnet** [comment] 2020-07-11 18:47
duplicate of https://github.com/esphome/issues/issues/1232

**Closed by glmnet** 2020-07-11 18:47 UTC
Labels: component: http_request
