### ISSUE TITLE
Corrupt packet while decoding name

### ISSUE THREAD

**Issue by ovanpeve** [esphome/issues#2788] opened 2021-12-06 10:19 UTC
### The problem

Hi there,

I've ESP8266 (NodeMCU v2) which all flood the logs with the following messages:

```
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7fa87dba00>)}
```
It looks it appeared with 2021.11.x (I don't remember having this previously)?

It may be related to mDNS, but the log doesn't show much where this error came from.

Thanks.

### Which version of ESPHome has the issue?

2021.11.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.11.5

### What platform are you using?

ESP8266

### Board

NodeMCU v2

### Component causing the issue

mDNS ?

### Example YAML snippet

```yaml
esphome:
  name: temper1
  platform: esp8266
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: "3e61e3711c02c31bb99ead1159a00e53"

wifi:
  ssid: "ssid"
  password: "password"
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temper1 Fallback Hotspot"
    password: "gBAOfZJs8O45"

captive_portal:


# DS18B20 Temperature Sensor
dallas:
  - pin: D2
    update_interval: 300s
  
sensor:
  - platform: dallas
    address: 0x493C01B456795848
    name: "Temperature dallas"
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/temper1.yaml...
INFO Starting log output from temper1.local using esphome API
{}
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}
INFO Successfully connected to temper1.local
[11:15:10][I][app:099]: ESPHome version 2021.11.4 compiled on Dec  6 2021, 10:31:02
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}
{'Corrupt packet received while decoding name': (<class 'zeroconf._exceptions.IncomingDecodeError'>,
                                                 IncomingDecodeError('Corrupt packet received while decoding name'),
                                                 <traceback object at 0x7f92e27300>)}

(and indefinitely flooding...)
```

**Comment by oxan** [comment] 2021-12-06 15:22
Duplicate of #2760.

**Closed by oxan** 2021-12-06 15:22 UTC
