### ISSUE TITLE
WebUI no longer displays buttons, switches, selectors, etc.

### ISSUE THREAD

**Issue by trip5** [esphome/issues#4626] opened 2023-06-26 20:00 UTC
### The problem

It used to be that the WebUI would display certain items.  I realize most of these items are available in Home Assistant but I got very used to one certain item NEVER being exposed to Home Assistant but always available in case I needed to restart a device:

```
button:
  - platform: restart
    id: "Restart"
    internal: true
```

Now it shows a line that says "Restart" but there is no button available.  I'm not sure which update nerfed this since I recently when from 2023.5... something to 2023.6.2... but one of the updates essentially took away all usefulness of the WebUI except displaying logs and the state of buttons, switches, etc.  I wish these things were still available.  Am I missing something?

### Which version of ESPHome has the issue?

2023.6.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

not related

### What platform are you using?

ESP8266

### Board

d1mini & esp32

### Component causing the issue

Webui

**Comment by ssieb** [comment] 2023-06-26 21:00
Duplicate of https://github.com/esphome/issues/issues/4606

**Closed by ssieb** 2023-06-26 21:00 UTC
