### ISSUE TITLE
Some yellow (warning?) info at log when update to newest ver

### ISSUE THREAD

**Issue by KitHubek** [esphome/issues#4591] opened 2023-06-22 10:03 UTC
### The problem

But update finally ok. Below some details:

Hardware: wt32-eth01
board: esp32doit-devkit-v1
framework: espidf
platform: platformio/espressif32@5.3.0

HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40404.0 (4.4.4) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5

Update via HA ESPHome addon

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.6.2

### What platform are you using?

ESP32

### Board

wt32-eth01

### Anything in the logs that might be useful for us?

```txt
Compiling /data/wt32-eth01-bt-proxy/.pioenvs/wt32-eth01-bt-proxy/bootloader_support/src/secure_boot.o
Compiling /data/wt32-eth01-bt-proxy/.pioenvs/wt32-eth01-bt-proxy/bootloader_support/src/flash_partitions.o
Compiling /data/wt32-eth01-bt-proxy/.pioenvs/wt32-eth01-bt-proxy/bootloader_support/src/flash_qio_mode.o
In file included from src/esphome.h:69,
                 from src/main.cpp:3:
src/esphome/core/time.h:11:13: warning: 'bool esphome::is_leap_year(uint32_t)' declared 'static' but never defined [-Wunused-function]
 static bool is_leap_year(uint32_t year);
             ^~~~~~~~~~~~
src/esphome/core/time.h:13:16: warning: 'uint8_t esphome::days_in_month(uint8_t, uint16_t)' declared 'static' but never defined [-Wunused-function]
 static uint8_t days_in_month(uint8_t month, uint16_t year);
                ^~~~~~~~~~~~~
Compiling /data/wt32-eth01-bt-proxy/.pioenvs/wt32-eth01-bt-proxy/bootloader_support/src/bootloader_flash_config_esp32.o
Compiling /data/wt32-eth01-bt-proxy/.pioenvs/wt32-eth01-bt-proxy/bootloader_support/src/bootloader_efuse.o
```

**Comment by randybb** [comment] 2023-06-22 10:09
Duplicate of #4581

**Closed by randybb** 2023-06-22 10:09 UTC
