### ISSUE TITLE
Add-on config 'auto_uart' is deprecated, use 'uart'

### ISSUE THREAD

**Issue by FoUStep** [esphome/issues#1849] opened 2021-02-16 13:45 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io OVA image.
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 mostly
**ESPHome version (latest production, beta, dev branch)**

ESPHome v1.16.1
**Affected component:**

WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

**Problem-relevant YAML-configuration entries:**
```yaml
No need.

```

**Logs (if applicable):**

```
WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of ESPHome

```

Additional information and things you've tried:
Reporting this to the maintainer. Tried to search for this, couldn't find it. Using ESPHome through Home Assistant

**Comment by randybb** [comment] 2021-02-16 14:56
Duplicate of #1837

**Closed by randybb** 2021-02-16 14:56 UTC
