### ISSUE TITLE
Unreported changes to eap authentication for esp8266 and esp32

### ISSUE THREAD

**Issue by nanctil** [esphome/issues#5959] opened 2024-06-23 20:25 UTC
### The problem

Recently updated esphome to find that nothing would compile because of configuration issues with eap authentication.

I initially got this error:
 `src/main.cpp: In function 'void setup()':
src/main.cpp:100:23: error: 'ESP_EAP_TTLS_PHASE2_MSCHAPV2' was not declared in this scope
       .ttls_phase_2 = ESP_EAP_TTLS_PHASE2_MSCHAPV2,
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:101:3: error: 'esphome::wifi::EAPAuth' has no non-static data member named 'ttls_phase_2'
   });
   ^
*** [.pioenvs/bathroom/src/main.cpp.o] Error 1
========================= [FAILED] Took 62.85 seconds =========================`

I noted that I adding `ttls_phase_2: mschapv2` to my eap config (which is optional as describe in the docs) enabled me to continue.
The config parser then warned me that I need to use the esp-idf framework to use `ttls_phase_2: mschapv2`. Which I proceeded to do.
This worked for esp32's, which is all well and good, but when I tried compiling for and esp8266 I noticed that the esp8266 platform config does not have the framework setting available.

Please Advise.

P.S I did later note that `ttls_phase_2: mschapv2` was no longer needed once I switched to `framework: esp-idf`

### Which version of ESPHome has the issue?

2024.6.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.6.4

### What platform are you using?

ESP8266

### Board

esp01_1m

### Component causing the issue

wifi

### Example YAML snippet

```yaml
wifi:
  fast_connect: false
  networks:
  - ssid: !secret wifi_ssidm
    hidden: true
    eap:
      username: !secret wifi_userm
      password: !secret wifi_passm
```

**Comment by randybb** [comment] 2024-06-23 21:04
Duplicate of https://github.com/esphome/issues/issues/5933

**Closed by randybb** 2024-06-23 21:04 UTC
