### ISSUE TITLE
 unexpected keyword argument 'required'

### ISSUE THREAD

**Issue by Spackstor** [esphome/issues#693] opened 2019-09-27 02:55 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

this is an installation problem, esphome python script related

**ESP (ESP32/ESP8266, Board/Sonoff):**
again not this far into the process

**Affected component:**

**Description of problem:**
esphome will not run
trying to invoke esphome after install get the following message

 File "/usr/local/lib/python2.7/dist-packages/voluptuous/schema_builder.py", li                                         ne 782, in extend
    return result_cls(result, required=result_required, extra=result_extra)
TypeError: __init__() got an unexpected keyword argument 'required'

**Problem-relevant YAML-configuration entries:** NA
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
had things running when i just used raspbian and set up a virtual environment venv

but then hassbian for the pi4 came out so I loaded it instead and have been getting the listed error (which goes away when i blank out a few python lines but other issues appear)

went back to raspbian but same issue, so i am thinking something has changed somewhere.

hassio may be better but installation information is outdated/incomplete/cryptic

**Comment by brandond** [comment] 2019-09-27 06:14
Duplicate of #666

**Closed** 2019-09-27 06:14 UTC
