### ISSUE TITLE
platform DHT crash with M5StickC

### ISSUE THREAD

**Issue by kktmp1** [esphome/issues#1302] opened 2020-06-17 15:01 UTC
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
docker home assistant
ESPHome 1.14.4 (edited)

**ESP (ESP32/ESP8266, Board/Sonoff):**
M5StickC

**Affected component:**
- platform: dht
DHT Temperature+Humidity

**Description of problem:**
M5Stick crashed if you include platform DHT in your yaml, removing that sensor all works perfect.
I've tried with 3 different sticks, same behaviour.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: m5stickempty
  platform: ESP32
  board: m5stick-c
  platformio_options:
    upload_speed: 1500000

wifi:
  ssid: "MOVISTAR"
  password: "removed"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "kkk"

ota:
  password: "kkk"

sensor:
  - platform: dht
    pin: GPIO26
    temperature:
      name: Temperature
    humidity:
      name: Humidity
    update_interval: 10s


```

**Logs (if applicable):**

```
INFO Reading configuration /config/esphome/m5stickempty.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/m5stickempty
Processing m5stickempty (board: m5stick-c; framework: arduino; platform: espressif32@1.12.1)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10004.200129 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/api_connection.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/api_pb2_service.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/api_server.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/list_entities.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/proto.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/subscribe_state.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/user_services.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/api/util.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/dht/dht.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/logger/logger.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/ota/ota_component.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/sensor/automation.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/sensor/filter.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/sensor/sensor.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/wifi/wifi_component.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/wifi/wifi_component_esp32.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/core/application.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/core/component.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/core/controller.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/core/esphal.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/core/log.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/core/preferences.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/esphome/core/util.cpp.o
Compiling /data/m5stickempty/.pioenvs/m5stickempty/src/main.cpp.o
Linking /data/m5stickempty/.pioenvs/m5stickempty/firmware.elf
Retrieving maximum program size /data/m5stickempty/.pioenvs/m5stickempty/firmware.elf
Checking size /data/m5stickempty/.pioenvs/m5stickempty/firmware.elf
Building /data/m5stickempty/.pioenvs/m5stickempty/firmware.bin
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  12.9% (used 42384 bytes from 327680 bytes)
Flash: [=====     ]  53.9% (used 882606 bytes from 1638400 bytes)
========================= [SUCCESS] Took 12.15 seconds =========================
INFO Successfully compiled program.
INFO Running:  platformio run -d /config/esphome/m5stickempty -t upload --upload-port /dev/ttyUSB0
Processing m5stickempty (board: m5stick-c; framework: arduino; platform: espressif32@1.12.1)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10004.200129 (1.0.4) 
 - tool-esptoolpy 1.20600.0 (2.6.0) 
 - tool-mkspiffs 2.230.0 (2.30) 
 - toolchain-xtensa32 2.50200.80 (5.2.0)
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|-- <DNSServer> 1.1.0
|   |-- <WiFi> 1.0
|-- <Update> 1.0
|-- <WiFi> 1.0
Retrieving maximum program size /data/m5stickempty/.pioenvs/m5stickempty/firmware.elf
Checking size /data/m5stickempty/.pioenvs/m5stickempty/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  12.9% (used 42384 bytes from 327680 bytes)
Flash: [=====     ]  53.9% (used 882606 bytes from 1638400 bytes)
Configuring upload protocol...
AVAILABLE: esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Use manually specified: /dev/ttyUSB0
Uploading /data/m5stickempty/.pioenvs/m5stickempty/firmware.bin
Serial port /dev/ttyUSB0
Connecting......
Chip is ESP32-PICO-D4 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, Embedded Flash, VRef calibration in efuse, Coding Scheme None
MAC: d8:a0:1d:56:0a:7c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 1500000
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Compressed 15872 bytes to 10319...

Writing at 0x00001000... (100 %)
Wrote 15872 bytes (10319 compressed) at 0x00001000 in 0.1 seconds (effective 1094.3 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 143...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (143 compressed) at 0x00008000 in 0.0 seconds (effective 6150.3 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...

Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.0 seconds (effective 16419.4 kbit/s)...
Hash of data verified.
Compressed 882720 bytes to 492378...

Writing at 0x00010000... (3 %)
Writing at 0x00014000... (6 %)
Writing at 0x00018000... (9 %)
Writing at 0x0001c000... (12 %)
Writing at 0x00020000... (16 %)
Writing at 0x00024000... (19 %)
Writing at 0x00028000... (22 %)
Writing at 0x0002c000... (25 %)
Writing at 0x00030000... (29 %)
Writing at 0x00034000... (32 %)
Writing at 0x00038000... (35 %)
Writing at 0x0003c000... (38 %)
Writing at 0x00040000... (41 %)
Writing at 0x00044000... (45 %)
Writing at 0x00048000... (48 %)
Writing at 0x0004c000... (51 %)
Writing at 0x00050000... (54 %)
Writing at 0x00054000... (58 %)
Writing at 0x00058000... (61 %)
Writing at 0x0005c000... (64 %)
Writing at 0x00060000... (67 %)
Writing at 0x00064000... (70 %)
Writing at 0x00068000... (74 %)
Writing at 0x0006c000... (77 %)
Writing at 0x00070000... (80 %)
Writing at 0x00074000... (83 %)
Writing at 0x00078000... (87 %)
Writing at 0x0007c000... (90 %)
Writing at 0x00080000... (93 %)
Writing at 0x00084000... (96 %)
Writing at 0x00088000... (100 %)
Wrote 882720 bytes (492378 compressed) at 0x00010000 in 8.0 seconds (effective 887.6 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
========================= [SUCCESS] Took 19.91 seconds =========================
INFO Successfully uploaded program.
INFO Starting log output from /dev/ttyUSB0 with baud rate 115200
[16:53:28]\xff[I][logger:156]: Log initialized
[16:53:28][C][ota:364]: There have been 0 suspected unsuccessful boot attempts.
[16:53:28][I][app:028]: Running through setup()...
[16:53:28][C][dht:011]: Setting up DHT...
[16:53:28][C][wifi:033]: Setting up WiFi...
[16:53:28][D][wifi:304]: Starting scan...
[16:53:28][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number) and consider manually specifying the DHT model using the model option.
[16:53:28][D][sensor:092]: 'Temperature': Sending state nan °C with 1 decimals of accuracy
[16:53:28][D][sensor:092]: 'Humidity': Sending state nan % with 0 decimals of accuracy
[16:53:29]Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
[16:53:29]Core 1 register dump:
[16:53:29]PC      : 0x4000c280  PS      : 0x00060634  A0      : 0x80089ce3  A1      : 0x3ffb1d00  
INFO Need to fetch platformio IDE-data, please stand by
INFO Running:  platformio run -d /config/esphome/m5stickempty -t idedata
[16:53:38]A2      : 0x3ffb0058  A3      : 0x3f40ebbc  A4      : 0x00000014  A5      : 0x3ffb1d00  
[16:53:38]A6      : 0x3ffb873c  A7      : 0x8d2a9bf8  A8      : 0x0000000a  A9      : 0x000000a5  
[16:53:38]A10     : 0x000000a5  A11     : 0x3ffb0060  A12     : 0x800d9538  A13     : 0x3ffb1bf0  
[16:53:38]A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000018  EXCCAUSE: 0x00000006  
[16:53:38]EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffe9  
[16:53:38]
[16:53:38]Backtrace: 0x4000c280:0x3ffb1d00 0x40089ce0:0x3ffb1d20 0x4008b924:0x3ffb1d40 0x4008b9b5:0x3ffb1d60 0x400db6f1:0x3ffb1d80 0x400dd1aa:0x3ffb1dd0 0x400e7833:0x3ffb1fb0 0x400890f5:0x3ffb1fd0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x40089ce0: vTaskSwitchContext at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:3507
WARNING Decoded 0x4008b924: _frxt_dispatch at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/portasm.S:406
WARNING Decoded 0x4008b9b5: vPortYield at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/portasm.S:555
WARNING Decoded 0x400db6f1: esphome::Application::setup() at /config/esphome/m5stickempty/src/esphome/core/application.cpp:54
WARNING Decoded 0x400dd1aa: setup() at /config/esphome/m5stickempty/src/main.cpp:155
WARNING Decoded 0x400e7833: loopTask(void*) at /root/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:14
WARNING Decoded 0x400890f5: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[16:53:38]
[16:53:38]Core 0 register dump:
[16:53:38]PC      : 0x4015d0f2  PS      : 0x00060b34  A0      : 0x800ea866  A1      : 0x3ffbc050  
WARNING Decoded 0x4015d0f2: esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/pm_esp32.c:492
[16:53:38]A2      : 0x00000000  A3      : 0x00000001  A4      : 0x00000000  A5      : 0x00000001  
[16:53:38]A6      : 0x00060120  A7      : 0x00000000  A8      : 0x800e97da  A9      : 0x3ffbc020  
[16:53:38]A10     : 0x00000000  A11     : 0x00000001  A12     : 0x80089308  A13     : 0x3ffb4630  
[16:53:38]A14     : 0x00000000  A15     : 0x3ffbbd40  SAR     : 0x00000000  EXCCAUSE: 0x00000006  
[16:53:38]EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
[16:53:38]
[16:53:38]Backtrace: 0x4015d0f2:0x3ffbc050 0x400ea863:0x3ffbc070 0x4008a8d9:0x3ffbc090 0x400890f5:0x3ffbc0b0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x4015d0f2: esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/pm_esp32.c:492
WARNING Decoded 0x400ea863: esp_vApplicationIdleHook at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/freertos_hooks.c:108
WARNING Decoded 0x4008a8d9: prvIdleTask at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:3507
WARNING Decoded 0x400890f5: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[16:53:38]
[16:53:38]Rebooting...
[16:53:38][I][logger:156]: Log initialized
[16:53:38][C][ota:364]: There have been 1 suspected unsuccessful boot attempts.
[16:53:38][I][app:028]: Running through setup()...
[16:53:38][C][dht:011]: Setting up DHT...
[16:53:38][C][wifi:033]: Setting up WiFi...
[16:53:38][D][wifi:304]: Starting scan...
[16:53:38][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number) and consider manually specifying the DHT model using the model option.
[16:53:38][D][sensor:092]: 'Temperature': Sending state nan °C with 1 decimals of accuracy
[16:53:38][D][sensor:092]: 'Humidity': Sending state nan % with 0 decimals of accuracy
[16:53:38]Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
[16:53:38]Core 1 register dump:
[16:53:38]PC      : 0x40089c7f  PS      : 0x00050634  A0      : 0x4008b927  A1      : 0x3ffb1d20  
WARNING Decoded 0x40089c7f: vTaskSwitchContext at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:3507
[16:53:39]A2      : 0x00050623  A3      : 0x00000001  A4      : 0x00000001  A5      : 0x3ffb1d20  
[16:53:39]A6      : 0x3ffb8768  A7      : 0x000001c5  A8      : 0x80089f09  A9      : 0x3ffb1d10  
[16:53:39]A10     : 0x00000003  A11     : 0x00060623  A12     : 0x800d5699  A13     : 0x3ffb1d00  
[16:53:39]A14     : 0x3ffb873c  A15     : 0x1a2e4384  SAR     : 0x00000018  EXCCAUSE: 0x00000006  
[16:53:39]EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffe9  
[16:53:39]
[16:53:39]Backtrace: 0x40089c7f:0x3ffb1d20 0x4008b924:0x3ffb1d40 0x4008b9b5:0x3ffb1d60 0x400db6f1:0x3ffb1d80 0x400dd1aa:0x3ffb1dd0 0x400e7833:0x3ffb1fb0 0x400890f5:0x3ffb1fd0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x40089c7f: vTaskSwitchContext at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:3507
WARNING Decoded 0x4008b924: _frxt_dispatch at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/portasm.S:406
WARNING Decoded 0x4008b9b5: vPortYield at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/portasm.S:555
WARNING Decoded 0x400db6f1: esphome::Application::setup() at /config/esphome/m5stickempty/src/esphome/core/application.cpp:54
WARNING Decoded 0x400dd1aa: setup() at /config/esphome/m5stickempty/src/main.cpp:155
WARNING Decoded 0x400e7833: loopTask(void*) at /root/.platformio/packages/framework-arduinoespressif32/cores/esp32/main.cpp:14
WARNING Decoded 0x400890f5: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[16:53:39]
[16:53:39]Core 0 register dump:
[16:53:39]PC      : 0x4015d0f2  PS      : 0x00060f34  A0      : 0x800ea866  A1      : 0x3ffbc050  
WARNING Decoded 0x4015d0f2: esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/pm_esp32.c:492
[16:53:39]A2      : 0x00000000  A3      : 0x00000001  A4      : 0x00000000  A5      : 0x00000001  
[16:53:39]A6      : 0x00060120  A7      : 0x00000000  A8      : 0x800e97da  A9      : 0x3ffbc020  
[16:53:39]A10     : 0x00000000  A11     : 0x00000001  A12     : 0x80089308  A13     : 0x3ffb5ad0  
[16:53:39]A14     : 0x00000000  A15     : 0x3ffbbd40  SAR     : 0x00000000  EXCCAUSE: 0x00000006  
[16:53:39]EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
[16:53:39]
[16:53:39]Backtrace: 0x4015d0f2:0x3ffbc050 0x400ea863:0x3ffbc070 0x4008a8d9:0x3ffbc090 0x400890f5:0x3ffbc0b0
WARNING Found stack trace! Trying to decode it
WARNING Decoded 0x4015d0f2: esp_pm_impl_waiti at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/pm_esp32.c:492
WARNING Decoded 0x400ea863: esp_vApplicationIdleHook at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/freertos_hooks.c:108
WARNING Decoded 0x4008a8d9: prvIdleTask at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/tasks.c:3507
WARNING Decoded 0x400890f5: vPortTaskWrapper at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1)
[16:53:39]
[16:53:39]Rebooting...
[16:53:39][I][logger:156]: Log initialized
[16:53:39][C][ota:364]: There have been 2 suspected unsuccessful boot attempts.
[16:53:39][I][app:028]: Running through setup()...
[16:53:39][C][dht:011]: Setting up DHT...
[16:53:39][C][wifi:033]: Setting up WiFi...
[16:53:39][D][wifi:304]: Starting scan...
[16:53:39][W][dht:060]: Invalid readings! Please check your wiring (pull-up resistor, pin number) and consider manually specifying the DHT model using the model option.
[16:53:39][D][sensor:092]: 'Temperature': Sending state nan °C with 1 decimals of accuracy
[16:53:39][D][sensor:092]: 'Humidity': Sending state nan % with 0 decimals of accuracy
[16:53:39]Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1)
[16:53:39]Core 1 register dump:
[16:53:39]PC      : 0x400dc2fc  PS    [D][wifi:319]: Found networks:
WARNING Decoded 0x400dc2fc: esphome::Scheduler::millis_() at /root/.platformio/packages/toolchain-xtensa32/xtensa-esp32-elf/include/c++/5.2.0/bits/stl_vector.h:932
[16:53:39][I][wifi:365]: - 'MOVISTAR' [redacted]▂▄▆█
[16:53:39][D][wifi:366]:     Channel: 11
[16:53:39][D][wifi:367]:     RSSI: -39 dB
[16:53:39][D][wifi:369]: - [redacted] [redacted]▂▄▆█
[16:53:39][D][wifi:369]: - [redacted] [redacted]▂▄▆█
[16:53:39][D][wifi:369]: - [redacted] [redacted]▂▄▆█
[16:53:39][I][wifi:193]: WiFi Connecting to 'MOVISTAR'...
[16:53:40][I][wifi:423]: WiFi Connected!
[16:53:40][C][wifi:283]:   SSID: [redacted]
[16:53:40][C][wifi:284]:   IP Address: 192.168.1.222
[16:53:40][C][wifi:286]:   BSSID: [redacted]
[16:53:40][C][wifi:287]:   Hostname: 'm5stickempty'
[16:53:40][C][wifi:291]:   Signal strength: -42 dB ▂▄▆█
[16:53:40][C][wifi:295]:   Channel: 11
[16:53:40][C][wifi:296]:   Subnet: 255.255.255.0
[16:53:41][C][wifi:297]:   Gateway: 192.168.1.1
[16:53:41][C][wifi:298]:   DNS1: 0.0.0.0
[16:53:41][C][wifi:299]:   DNS2: 0.0.0.0
[16:53:41][C][ota:029]: Over-The-Air Updates:
[16:53:41][C][ota:030]:   Address: 192.168.1.222:3232
[16:53:41][C][ota:032]:   Using Password.
[16:53:41][W][ota:036]: Last Boot was an unhandled reset, will proceed to safe mode in 0 restarts
[16:53:41][I][app:058]: setup() finished successfully!
[16:53:41][I][ota:379]: Waiting for OTA attempt.
[16:53:41][I][app:100]: ESPHome version 1.14.4 compiled on Jun 17 2020, 16:53:03
[16:53:41][C][wifi:415]: WiFi:
[16:53:41][C][wifi:283]:   SSID: [redacted]
[16:53:41][C][wifi:284]:   IP Address: 192.168.1.222
[16:53:41][C][wifi:286]:   BSSID: [redacted]
[16:53:41][C][wifi:287]:   Hostname: 'm5stickempty'
[16:53:41][C][wifi:291]:   Signal strength: -36 dB ▂▄▆█
[16:53:41][C][wifi:295]:   Channel: 11
[16:53:41][C][wifi:296]:   Subnet: 255.255.255.0
[16:53:41][C][wifi:297]:   Gateway: 192.168.1.1
[16:53:41][C][wifi:298]:   DNS1: 0.0.0.0
[16:53:41][C][wifi:299]:   DNS2: 0.0.0.0
[16:53:41][C][logger:175]: Logger:
[16:53:41][C][logger:176]:   Level: DEBUG
[16:53:41][C][logger:177]:   Log Baud Rate: 115200
[16:53:41][C][logger:178]:   Hardware UART: UART0
[16:53:41][C][captive_portal:169]: Captive Portal:
[16:53:41][C][ota:029]: Over-The-Air Updates:
[16:53:41][C][ota:030]:   Address: 192.168.1.222:3232
[16:53:41][C][ota:032]:   Using Password.
[16:53:41][W][ota:036]: Last Boot was an unhandled reset, will proceed to safe mode in 0 restarts

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment] 2020-06-17 23:14
There is a known bug in v1.14.4. Which version are you running?

**Comment by kktmp1** [comment] 2020-06-19 06:26
> There is a known bug in v1.14.4. Which version are you running?

Yes, sorry, It's since i've updated to 1.14.4.

I also have another problems with some M5StickCs and wifi updates.  Maybe I should downgraded?

**Comment by glmnet** [comment] 2020-06-25 12:11
Duplicate of #1276 

if you have another issues please open another one. Thanks

**Closed by glmnet** 2020-06-25 12:11 UTC
